<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="瑞鹤仙心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 86" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第1章：瑞鹤仙简介与成长历程" POSITION="right">
  </node>
    <node TEXT="1.1 个人背景" POSITION="right">
      <node TEXT="**年代**：80后" />
      <node TEXT="**籍贯**：湖北宜昌人" />
      <node TEXT="**教育**：毕业于上海某著名高校" />
      <node TEXT="**席位**：" />
      <node TEXT="湖北宜昌两个某席位" />
    </node>
    <node TEXT="1.2 成长轨迹（传奇经历）" POSITION="right">
      <node TEXT="**2009年**：入市，当时还从事程序员工作" />
      <node TEXT="**2011年**：将父母支持创业的50万资金亏到20多万" />
      <node TEXT="创业失败、股市腰斩" />
      <node TEXT="到了人生的最低谷，一片黑暗" />
      <node TEXT="2011年底过年前，整个人崩溃，甚至想到了极端的念头" />
    </node>
    <node TEXT="1.3 历史地位" POSITION="right">
      <node TEXT="**熊市出英雄**：在2012年大熊市中完成不可思议的逆转" />
      <node TEXT="**自学成才**：没有任何名师指导，完全靠自己悟道" />
      <node TEXT="**奉献精神**：在网上留下大量宝贵文字，帮助后辈" />
    </node>
    <node TEXT="1.4 核心启示" POSITION="right">
      <node TEXT="&gt; "往往在万念俱灰，人生看不到出路的时候可能出现大逆转，但是这要求你不能放弃。"" />
    </node>
    <node TEXT="1.5 成功关键因素" POSITION="right">
      <node TEXT="1. **不放弃**：在最绝望的时候也没有放弃
2. **疯狂学习**：断绝一切社交，日以继夜的复盘
3. **悟道**：2011年春节期间开始悟道
4. **积累信心**：通过连续3次、5次、乃至1..." />
    </node>
  <node TEXT="第2章：核心交易理念" POSITION="right">
  </node>
    <node TEXT="2.1 稳定盈利的本质" POSITION="right">
      <node TEXT="稳定盈利不是大赚大赔" />
      <node TEXT="而是不断的积累小胜利" />
      <node TEXT="通过连续3次、5次、乃至10次的小的连续盈利积累起来的信心" />
    </node>
    <node TEXT="2.2 熊市是金子，是财富" POSITION="right">
      <node TEXT="在熊市中做到稳定盈利，才是最扎实的练就了炒股的技术" />
      <node TEXT="否则就算遇到好的市场环境，也会徘徊在大赚大赔之间" />
      <node TEXT="最困难的时候都通过操作赚了很多，往后也就没有什么过不去的坎了" />
    </node>
    <node TEXT="2.3 不要心存侥幸" POSITION="right">
      <node TEXT="如果要持续稳定的盈利，那么必然要求在熊市中做到" />
      <node TEXT="这样才是最扎实的练就了炒股的技术" />
      <node TEXT="否则就算遇到好的市场环境，也会徘徊在大赚大赔之间" />
    </node>
    <node TEXT="2.4 职业炒股的真谛" POSITION="right">
      <node TEXT="在没有稳定盈利的情况下职业炒股，恰恰是最能提高自己的" />
      <node TEXT="因为你才能精钻进去，仔细研究自己为什么没有稳定盈利" />
      <node TEXT="并且通过职业炒股的操盘来实践自己的改进的战法" />
    </node>
    <node TEXT="2.5 核心要点总结" POSITION="right">
      <node TEXT="1. 稳定盈利的本质是做"确定性"
2. 熊市是金子，是财富
3. 不要心存侥幸，指望牛市翻身
4. 职业炒股需要专注，心无旁骛
5. 在熊市中做到稳定盈利，才是最扎实的" />
    </node>
  <node TEXT="第3章：情绪周期与大盘预判" POSITION="right">
  </node>
    <node TEXT="3.1 重个股、轻指数的错误" POSITION="right">
      <node TEXT="做个股必须结合大盘" />
      <node TEXT="要正确的预测大盘" />
      <node TEXT="才能提前于别人买入" />
    </node>
    <node TEXT="3.2 不预测、只跟随的错误" POSITION="right">
      <node TEXT="不预测、只跟随是极大错误的" />
      <node TEXT="你要做的不光是不去预测，反而是要更加努力的研究如何预测" />
      <node TEXT="如何预判，如何根据过去未来和当日盘面的去预判第二天的走势" />
      <node TEXT="只需预测1天就足够了，然后不断重复做这种预测1天的做法" />
    </node>
    <node TEXT="3.3 如何预判大盘" POSITION="right">
      <node TEXT="只需预测1天就足够了" />
      <node TEXT="然后不断重复做这种预测1天的做法" />
      <node TEXT="做好了，你每天都是胜利的" />
    </node>
    <node TEXT="3.4 核心要点总结" POSITION="right">
      <node TEXT="1. 重个股、轻指数是绝对错误的
2. 不预测、只跟随是极大错误的
3. 最高明的预测是买在转折处
4. 只需预测1天就足够了
5. 做个股必须结合大盘" />
    </node>
  <node TEXT="第4章：多模式战法" POSITION="right">
  </node>
    <node TEXT="4.1 技术要全面" POSITION="right">
      <node TEXT="打板只是其中一种技术" />
      <node TEXT="技术要全面" />
      <node TEXT="根据个股技术特征和大盘环境选择合适模式" />
    </node>
    <node TEXT="4.2 瑞鹤仙的多种模式" POSITION="right">
      <node TEXT="低吸" />
      <node TEXT="追涨" />
      <node TEXT="打板" />
      <node TEXT="做首板" />
      <node TEXT="做1进2" />
    </node>
    <node TEXT="4.3 掌握的方法越多，赢面越大" POSITION="right">
      <node TEXT="现在股市越来越复杂，要求的综合炒股技术和素质也越来越高" />
      <node TEXT="咱们股民也要与时俱进，综合全面的提升自己" />
      <node TEXT="以使得自己不会被市场所淘汰" />
    </node>
    <node TEXT="4.4 核心要点总结" POSITION="right">
      <node TEXT="1. 做股票技术要全面
2. 打板只是其中一种技术
3. 掌握的方法越多，赢面越大
4. 能应付的情况就越多
5. 要与时俱进，综合全面的提升自己" />
    </node>
  <node TEXT="第5章：资金管理与风险控制" POSITION="right">
  </node>
    <node TEXT="5.1 小资金也要分仓，也不加杠杆" POSITION="right">
      <node TEXT="小资金做大需要稳定的成功率" />
      <node TEXT="如果像你全部重仓做一只票，你的模式是不稳定的，容易大赚大亏" />
      <node TEXT="理想论坛每次比赛冠军都是长期做出来的，不是靠运气，是靠稳定的模式，靠复利做出来" />
      <node TEXT="没有自己的方法，一个亿的资金去做也是韭菜" />
    </node>
    <node TEXT="5.2 融资资金是不能补仓买入的" POSITION="right">
      <node TEXT="当你决定要融资买入一个股票的时候，必须有100%的把握，99%都不行" />
      <node TEXT="否则宁可等待" />
    </node>
    <node TEXT="5.3 止损的重要性" POSITION="right">
      <node TEXT="一旦不及预期的走势就赶紧割肉" />
      <node TEXT="超短就是做隔日，一旦不达预期就是走人" />
      <node TEXT="必须要杀伐果断" />
    </node>
    <node TEXT="5.4 控制回撤" POSITION="right">
      <node TEXT="一般很少1个月翻倍" />
      <node TEXT="而是一个月30%左右，3个月翻倍" />
      <node TEXT="平时资产呈现小碎步缓慢爬升，积累一定利润后再加速爆发" />
      <node TEXT="然后再恢复到小碎步爬升，如此循环" />
      <node TEXT="因为是稳定盈利，所以操作手法以有把握为准则" />
    </node>
    <node TEXT="5.5 核心要点总结" POSITION="right">
      <node TEXT="1. 小资金也要分仓，也不加杠杆
2. 融资资金是不能补仓买入的
3. 对于已经淘汰的题材，反弹就赶紧走
4. 控制回撤，大幅回撤几乎为0
5. 稳定盈利的外在表现是小碎步缓慢爬升" />
    </node>
  <node TEXT="第6章：心态管理与自我修正" POSITION="right">
  </node>
    <node TEXT="6.1 做短线就是不断自我否定，不断修正自己" POSITION="right">
      <node TEXT="&gt; "做短线就是不断自我否定，不断修正自己的地方。"" />
    </node>
    <node TEXT="6.2 悟道的标准" POSITION="right">
      <node TEXT="&gt; "你长期做股票，你发现收益曲线稳定了，三到六个月，关键在于稳定，做股票不要追捧梭哈一个票，如果赚了容易让自己狂妄，买别的票你也容易梭哈其他票，所以短线选手要明白赚钱是行情给与的，不要重仓去赌..." />
    </node>
    <node TEXT="6.3 不要梭哈" POSITION="right">
      <node TEXT="如果赚了容易让自己狂妄" />
      <node TEXT="买别的票你也容易梭哈其他票" />
      <node TEXT="短线选手要明白赚钱是行情给与的" />
      <node TEXT="不要重仓去赌" />
      <node TEXT="很多人一输就没有赌的资本了" />
    </node>
    <node TEXT="6.4 做短线需要天赋和理解力" POSITION="right">
      <node TEXT="&gt; "做短线需要天赋和理解力的，做短线要做出来：首先模式是对的，天天换模式是不行的，要不断修正调整自己，做股票好的人总能够找到规律，善于总结，做短线：要有短线世界观，龙头补涨切换。"" />
    </node>
    <node TEXT="6.5 核心要点总结" POSITION="right">
      <node TEXT="1. 做短线就是不断自我否定，不断修正自己
2. 悟道的标准是收益曲线稳定三到六个月
3. 不要梭哈，梭哈大亏会让你心态崩了
4. 做短线需要天赋和理解力
5. 做股票好的人总能够找到规律，善于总结" />
    </node>
  <node TEXT="第7章：价值投资与投机技术的结合" POSITION="right">
  </node>
    <node TEXT="7.1 伪价值投资" POSITION="right">
      <node TEXT="高位信了各种吹大故事的逻辑" />
      <node TEXT="最终由于不止损，一波的回撤是相当大的" />
      <node TEXT="甚至拿的杠杆做的趋势，都有爆仓的风险" />
    </node>
    <node TEXT="7.2 真正的价值投资" POSITION="right">
      <node TEXT="必须非常清楚的了解这个企业" />
      <node TEXT="包括它的优点与缺点" />
      <node TEXT="才能真正了解这个公司是否被低估，是否被错杀" />
    </node>
    <node TEXT="7.3 价值投资+投机技术的结合" POSITION="right">
      <node TEXT="这并不是追板，而是买在温和上涨的途中" />
      <node TEXT="但是是基于价值分析后的投机买入" />
      <node TEXT="而且在持有的头1周股价也没有上串下跳，不会暴涨暴跌" />
      <node TEXT="给予充分的参与机会，很适合老股民介入" />
      <node TEXT="五粮液：基于价值分析后的投机买入" />
    </node>
    <node TEXT="7.4 核心要点总结" POSITION="right">
      <node TEXT="1. 绝大部分趋势股，都是披着外衣的投机股
2. 伪价值投资：高位信了各种吹大故事的逻辑，不止损
3. 真正的价值投资：必须非常清楚的了解这个企业
4. 价值投资+投机技术的结合是最好的
5. 买在温..." />
    </node>
  <node TEXT="第8章：复盘与交割单研究" POSITION="right">
  </node>
    <node TEXT="8.1 交割单中有黄金" POSITION="right">
      <node TEXT="交割单中有黄金" />
      <node TEXT="无论是高手还是低手，每一个赚钱的交割单中都有黄金" />
      <node TEXT="每一个亏钱的交割单中也有黄金" />
    </node>
    <node TEXT="8.2 失败的交割单的重要性远超成功的交割单" POSITION="right">
      <node TEXT="你要多想，当时为何能行，如今你的操作到底出了什么问题" />
      <node TEXT="我以前经常说，要反复看自己的交割单，越是失败的交割单越要去逼着自己看" />
      <node TEXT="要多想想，如果是错误的决定，当时买卖的瞬间为何自己要那么做" />
      <node TEXT="那么现在看来，如果现在发生类似的情况，自己有没有能够说服自己的逻辑去阻止自己做这种错误的操作" />
    </node>
    <node TEXT="8.3 如何复盘" POSITION="right">
      <node TEXT="每天复盘" />
      <node TEXT="每周总结" />
      <node TEXT="每月提升" />
    </node>
    <node TEXT="8.4 核心要点总结" POSITION="right">
      <node TEXT="1. 交割单中有黄金
2. 失败的交割单的重要性远超成功的交割单
3. 要反复看自己的交割单
4. 越是失败的交割单越要去逼着自己看
5. 必须是自己能够说服自己的逻辑" />
    </node>
  <node TEXT="第9章：熊市操作策略" POSITION="right">
  </node>
    <node TEXT="9.1 熊市中的稳定盈利" POSITION="right">
      <node TEXT="在熊市中做到稳定盈利，才是最扎实的练就了炒股的技术" />
      <node TEXT="否则就算遇到好的市场环境，也会徘徊在大赚大赔之间" />
      <node TEXT="最困难的时候都通过操作赚了很多，往后也就没有什么过不去的坎了" />
    </node>
    <node TEXT="9.2 熊市中的策略" POSITION="right">
      <node TEXT="全国股民都绝望的一年" />
      <node TEXT="经常单日成交量沪市都不到400亿的一年" />
      <node TEXT="瑞鹤仙却在这一年完成了不可思议的逆转" />
      <node TEXT="要有勇气在低位试错" />
      <node TEXT="要敢于在分歧的时候介入" />
    </node>
    <node TEXT="9.3 熊市中的心态" POSITION="right">
      <node TEXT="第一天杀跌是很恐怖的" />
      <node TEXT="但是第二天的杀跌，如果还是持续的话，尾盘就可以找买点" />
      <node TEXT="第三天肯定会有情绪的修复" />
    </node>
    <node TEXT="9.4 核心要点总结" POSITION="right">
      <node TEXT="1. 在熊市中做到稳定盈利，才是最扎实的
2. 熊市操作需要勇气在低位试错
3. 要敢于在分歧的时候介入
4. 要严格控制仓位
5. 第三天肯定会有情绪的修复" />
    </node>
  <node TEXT="第10章：主升浪操作技巧" POSITION="right">
  </node>
    <node TEXT="10.1 主升浪可遇而不可求" POSITION="right">
      <node TEXT="还是要靠笨办法，每天复盘翻一遍个股" />
      <node TEXT="把走势符合主升浪雏形的找出来" />
      <node TEXT="然后研究其公告啊，题材啊，预期啊，F10等等" />
      <node TEXT="然后再不断跟踪" />
    </node>
    <node TEXT="10.2 主升浪的操作要点" POSITION="right">
      <node TEXT="这一段（86.5万——&gt;155万）我自己也非常满意，可以说操作没有任何瑕疵" />
      <node TEXT="达到了自己的理想状态" />
    </node>
    <node TEXT="10.3 主升浪的卖出" POSITION="right">
      <node TEXT="不贪，不贪才能大赚" />
      <node TEXT="这波做大化总资产增值25%已经够了，有了资金就有了主动权（止盈）" />
      <node TEXT="市场环境恶化，周一又要停牌1小时，卖出了风险，得到了利润（风控）" />
      <node TEXT="个股技术面原因" />
    </node>
    <node TEXT="10.4 核心要点总结" POSITION="right">
      <node TEXT="1. 主升浪可遇而不可求
2. 还是要靠笨办法，每天复盘翻一遍个股
3. 并不是简单的半仓滚动
4. 最后2天连续大阳我是满仓，坚决不做任何T
5. 不贪，不贪才能大赚" />
    </node>
  <node TEXT="第11章：题材预判与板块轮动" POSITION="right">
  </node>
    <node TEXT="11.1 题材预判的重要性" POSITION="right">
      <node TEXT="&gt; "先于市场发现可发酵的舆论事件，是一种高效的赚钱模式。"" />
    </node>
    <node TEXT="11.2 板块轮动的研究" POSITION="right">
      <node TEXT="房地产已经持续走牛一段时间了，无论是大盘地产股还是小盘地产股，都有持续的赚钱效应" />
      <node TEXT="地产股业绩拐点预期是和经济复苏预期一致的" />
      <node TEXT="中航地产，业绩并不是不理想，根据3季报，目前市盈率才15倍" />
      <node TEXT="要搞清楚一个股为什么牛不能就看表面" />
      <node TEXT="中航地产因为业绩公告后才引发爆炒，所以不惧股东减持，越减持越长" />
    </node>
    <node TEXT="11.3 题材的持续性" POSITION="right">
      <node TEXT="**判断题材持续性的因素**：
1. 题材的强度
2. 题材的级别
3. 题材的发酵程度
4. 市场的认可度" />
    </node>
    <node TEXT="11.4 核心要点总结" POSITION="right">
      <node TEXT="1. 先于市场发现可发酵的舆论事件，是一种高效的赚钱模式
2. 要搞清楚一个股为什么牛不能就看表面
3. 要研判板块轮动
4. 要判断题材的持续性
5. 要有足够的信息渠道，大量无用信息去过滤" />
    </node>
  <node TEXT="第12章：实战案例分析" POSITION="right">
  </node>
    <node TEXT="12.1 案例一：轴研科技（高低切模式）" POSITION="right">
      <node TEXT="**操作**：2板切入" />
      <node TEXT="**收益**：吃了4个板" />
      <node TEXT="**模式**：高低切模式" />
      <node TEXT="**成功关键**：" />
      <node TEXT="低位试错" />
    </node>
    <node TEXT="12.2 案例二：宏润建设（高低切模式）" POSITION="right">
      <node TEXT="**操作**：3板隔夜顶的一字" />
      <node TEXT="**收益**：也吃了4个板" />
      <node TEXT="**模式**：高低切模式" />
      <node TEXT="**成功关键**：" />
      <node TEXT="敢于顶一字" />
    </node>
    <node TEXT="12.3 案例三：成飞集成（重仓操作）" POSITION="right">
      <node TEXT="**操作**：第一次进出大约盈利30多万，第二次进出盈利115.69万" />
      <node TEXT="**模式**：重仓操作" />
      <node TEXT="**成功关键**：" />
      <node TEXT="对题材深度有预期" />
      <node TEXT="敢于重仓" />
    </node>
    <node TEXT="12.4 案例四：中航地产（接力板）" POSITION="right">
      <node TEXT="**操作**：买入做接力板" />
      <node TEXT="**模式**：接力板" />
      <node TEXT="**成功关键**：" />
      <node TEXT="它有业绩增长这个题材" />
      <node TEXT="其次小非减持，也算是一个炒作理由" />
    </node>
    <node TEXT="12.5 核心要点总结" POSITION="right">
      <node TEXT="1. 轴研科技：2板切入，吃了4个板
2. 宏润建设：3板隔夜顶的一字，吃了4个板
3. 成飞集成：重仓操作，盈利115.69万
4. 中航地产：接力板，成功关键是对题材的深度理解
5. 成功关键：敢..." />
    </node>
  <node TEXT="第13章：常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="13.1 误区一：认为稳定盈利了再职业" POSITION="right">
      <node TEXT="**错误理解**：稳定盈利了再职业" />
      <node TEXT="**正确理解**：" />
      <node TEXT="不要听别人说的稳定盈利了再职业" />
      <node TEXT="试问：一边工作一边炒股都稳定盈利了那还需要职业吗？" />
      <node TEXT="干一件事情就要专注的把它做好，所谓心无旁骛" />
    </node>
    <node TEXT="13.2 误区二：重个股、轻指数" POSITION="right">
      <node TEXT="**错误理解**：重个股、轻指数" />
      <node TEXT="**正确理解**：" />
      <node TEXT="这个观念我认为是绝对错误的" />
      <node TEXT="因为如果你不能正确的预测大盘，那么你就不能提前于别人买入" />
      <node TEXT="最终你只能被大盘和市场牵着鼻子走，陷入被动" />
    </node>
    <node TEXT="13.3 误区三：不预测、只跟随" POSITION="right">
      <node TEXT="**错误理解**：不预测、只跟随" />
      <node TEXT="**正确理解**：" />
      <node TEXT="这个观点的前后2句话本身就是极大矛盾的" />
      <node TEXT="你要做的不光是不去预测，反而是要更加努力的研究如何预测" />
      <node TEXT="如何预判，如何根据过去未来和当日盘面的去预判第二天的走势" />
    </node>
    <node TEXT="13.4 误区四：心存侥幸，指望牛市翻身" POSITION="right">
      <node TEXT="**错误理解**：心存侥幸，指望牛市翻身" />
      <node TEXT="**正确理解**：" />
      <node TEXT="如果心存侥幸，指望一个牛市就翻身，那我想最终可能不能如愿以偿" />
      <node TEXT="如果要持续稳定的盈利，那么必然要求在熊市中做到" />
      <node TEXT="这样才是最扎实的练就了炒股的技术" />
    </node>
    <node TEXT="13.5 核心要点总结" POSITION="right">
      <node TEXT="1. 不要稳定盈利了再职业，职业炒股恰恰是最能提高自己的
2. 重个股、轻指数是绝对错误的
3. 不预测、只跟随是极大错误的
4. 不要心存侥幸，指望牛市翻身
5. 要更加努力的研究如何预测，如何预判" />
    </node>
  <node TEXT="第14章：职业炒股的心路历程" POSITION="right">
  </node>
    <node TEXT="14.1 职业炒股的困难" POSITION="right">
      <node TEXT="面临的各种困难和挫折" />
      <node TEXT="自信的丧失" />
      <node TEXT="经济压力" />
      <node TEXT="社会压力" />
    </node>
    <node TEXT="14.2 职业炒股的建议" POSITION="right">
      <node TEXT="&gt; "年龄不饶人，岁数越大职业越不好，因为岁数大了后如果职业无成就，那么再回头工作就更难适应了。所以要么不要去职业炒股，要么就要下决心趁年轻大胆的去尝试，挑战自我，否则最后肯定 会后悔的！"" />
    </node>
    <node TEXT="14.3 职业炒股的心得" POSITION="right">
      <node TEXT="最开心的日子真的很少" />
      <node TEXT="而收盘后充满懊恼和遗憾甚至悔恨的日子却很多" />
      <node TEXT="要不断的复盘，不断的研究" />
      <node TEXT="要相信自己，只要努力，就一定能够成功" />
    </node>
    <node TEXT="14.4 核心要点总结" POSITION="right">
      <node TEXT="1. 职业炒股不容易，面临的各种困难和挫折
2. 只能来只持续稳定的盈利，只有这样才能给自己希望
3. 年龄不饶人，岁数越大职业越不好
4. 要么不要去职业炒股，要么就要下决心趁年轻大胆的去尝试
5...." />
    </node>
  <node TEXT="第15章：总结与行动计划" POSITION="right">
  </node>
    <node TEXT="15.1 瑞鹤仙心法核心总结" POSITION="right">
      <node TEXT="80后，湖北宜昌人，毕业于上海某著名高校" />
      <node TEXT="2009年入市，2011年亏到20多万，到了人生的最低谷" />
      <node TEXT="2011年春节期间开始悟道" />
      <node TEXT="2012年大熊市中完成不可思议的逆转" />
      <node TEXT="2015年初资金过亿" />
    </node>
    <node TEXT="15.2 给初学者的建议" POSITION="right">
      <node TEXT="#### 第一阶段：打好基础（1-3个月）
1. 理解稳定盈利的本质
2. 学习基本的技术分析
3. 培养盘感
4. 小资金练手" />
    </node>
    <node TEXT="15.3 每日自我训练计划" POSITION="right">
      <node TEXT="[ ] 查看隔夜消息" />
      <node TEXT="[ ] 分析昨日涨停板" />
      <node TEXT="[ ] 预判今日热点" />
      <node TEXT="[ ] 制定操作计划" />
      <node TEXT="[ ] 观察大盘走势" />
    </node>
    <node TEXT="15.4 核心要点总结" POSITION="right">
      <node TEXT="1. 瑞鹤仙心法核心是熊市出英雄
2. 初学者需要循序渐进
3. 每日训练计划很重要
4. 不断学、不断进化
5. 最终形成自己的交易系统" />
    </node>
  <node TEXT="附录：快速参考指南" POSITION="right">
  </node>
    <node TEXT="A. 瑞鹤仙心法速查表" POSITION="right">
      <node TEXT="| 类别 | 核心内容 | 关键点 |
|------|----------|--------|
| **成长历程** | 80后，2009年入市，2015年过亿 | 熊市出英雄 |
| **交易理念..." />
    </node>
    <node TEXT="B. 每日操作检查清单" POSITION="right">
      <node TEXT="[ ] 隔夜消息是否重大？" />
      <node TEXT="[ ] 昨日涨停板质量如何？" />
      <node TEXT="[ ] 今日可能热点是什么？" />
      <node TEXT="[ ] 操作计划是否制定？" />
      <node TEXT="[ ] 大盘走势是否符合预期？" />
    </node>
    <node TEXT="C. 常见错误与纠正" POSITION="right">
      <node TEXT="| 常见错误 | 表现 | 纠正方法 |
|----------|------|----------|
| 稳定盈利了再职业 | 一边工作一边炒股 | 职业炒股恰恰是最能提高自己的 |
| 重个股、轻..." />
    </node>
    <node TEXT="D. 进阶学资源" POSITION="right">
      <node TEXT="#### 同类型游资心法
1. **小鳄鱼**：超短线核心、二板战法
2. **92科比**：大道无形、情绪周期四阶段
3. **赵老哥**：连板战法、题材炒作本质
4. **炒股养家**：情绪周期、..." />
    </node>
</node>
</map>