<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="ASKING心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 68" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第1章：ASKING简介与成长历程" POSITION="right">
  </node>
    <node TEXT="1.1 个人背景" POSITION="right">
      <node TEXT="**真名**：邱宝裕" />
      <node TEXT="**网名**：ASKING（A股之神）" />
      <node TEXT="**出生年代**：1970年代" />
      <node TEXT="**籍贯**：福建福州" />
      <node TEXT="**入市时间**：1994年" />
    </node>
    <node TEXT="1.2 资金增长历程" POSITION="right">
      <node TEXT="**1994年**：第一次入市，上证指数从1500点一直绵绵下跌" />
      <node TEXT="**1997年**：期货打暴，钱没了，只好再杀回股市" />
      <node TEXT="**1998年春节后**：第三次重返股市，借了10几万" />
      <node TEXT="**2003年下半年**：资金量达到一定的规模" />
      <node TEXT="**2004年**：资金从10几万到几千万，成交量从两三百万到7,8个亿" />
    </node>
    <node TEXT="1.3 操盘席位" POSITION="right">
      <node TEXT="**席位**：兴业证券股份有限公司福州湖东路证券营业部" />
      <node TEXT="**操作特点**：专做人气股、领涨股、龙头股" />
    </node>
    <node TEXT="1.4 成长关键词" POSITION="right">
      <node TEXT="**超短线**：从1998年到2006年7月23日，专注超短线" />
      <node TEXT="**龙头战法**：只做人气股、领涨股、龙头股" />
      <node TEXT="**守株待兔**：短线介入点，等待最强的那只股票出现" />
      <node TEXT="**仓位管理**：半仓操作，确认后加仓到全仓" />
      <node TEXT="**心态控制**：十分里边，心态、控制力占7分，技术占3分" />
    </node>
  <node TEXT="第2章：核心交易理念" POSITION="right">
  </node>
    <node TEXT="2.1 对市场的理解力" POSITION="right">
      <node TEXT="交易是所有分析以后的结果，并不是盘口随意的追涨" />
      <node TEXT="做人气股、领涨股时资金最安全，效率最高" />
      <node TEXT="人气股不仅仅是热点，还是热点中的焦点" />
      <node TEXT="一般的资金只是发现和跟随，宁波解放南路是发掘和引导，技术含量要高得多" />
    </node>
    <node TEXT="2.2 下决心付诸行动的决断力" POSITION="right">
      <node TEXT="邱宝裕在1997年期货打暴，钱没了" />
      <node TEXT="他妈很支持他，到处张罗，总算凑了10来万" />
      <node TEXT="于是1998年春节后，他又杀回来了" />
      <node TEXT="其实这是他第三次重返股市了，最早要从1994年说起" />
    </node>
    <node TEXT="2.3 核心操作观念" POSITION="right">
      <node TEXT="选股很重要，是决定性的前提，但选股还不是全部" />
      <node TEXT="任何一种操作方法，哪怕是做下跌通道的一个小反抽，只要是不参与任何级别调整，买了就为了马上挣钱，这种方法都是短线" />
      <node TEXT="说白了，不参与任何性质整理！" />
      <node TEXT="所以，就我的看法，荣展做的只是超强势股，并非真正的龙头，我和职业炒手兄所找的才是龙头" />
    </node>
    <node TEXT="2.4 龙头战法" POSITION="right">
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
      <node TEXT="我的追涨操作为什么都出现在大盘已大涨的情况下。原因很简单，我不能确认每一次大盘是否能继续向上，所以就挑最强的股票上" />
      <node TEXT="大盘如果还向好，最强的股票就会再次大幅向上；大盘如果不行，则最强的股票通常还能横几天，可以果断退出" />
    </node>
  <node TEXT="第3章：选股体系" POSITION="right">
  </node>
    <node TEXT="3.1 选股的原则" POSITION="right">
      <node TEXT="做人气股、领涨股时资金最安全，效率最高" />
      <node TEXT="人气股不仅仅是热点，还是热点中的焦点" />
      <node TEXT="只做超强势股的追涨和守株待兔" />
      <node TEXT="选股很重要，是决定性的前提" />
      <node TEXT="龙头只所以安全，就在于与大盘转势共振" />
    </node>
    <node TEXT="3.2 选股的方法" POSITION="right">
      <node TEXT="需要绝对的耐心" />
      <node TEXT="在一轮经典的下跌过后，市场面临转势，但我们不知道谁会先涨" />
      <node TEXT="资金量大的操作必然会提前布局，而我们需要的就是睁大眼睛，等待最强的那只股票出现，然后闭着眼睛进入就可以了" />
      <node TEXT="需要经验来确认" />
      <node TEXT="龙头需要技术吗，不需要，要的是临阵时的果敢和勇气" />
    </node>
    <node TEXT="3.3 选股的注意事项" POSITION="right">
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
      <node TEXT="说白了，不参与任何性质整理！" />
      <node TEXT="任何一种操作方法，只要是参与了任何级别调整，买了不是为了马上挣钱，这种方法都不是短线" />
      <node TEXT="荣展做的只是超强势股，并非真正的龙头" />
      <node TEXT="我和职业炒手兄所找的才是龙头" />
    </node>
  <node TEXT="第4章：买入时机把握" POSITION="right">
  </node>
    <node TEXT="4.1 买入时机的选择" POSITION="right">
      <node TEXT="龙头只存在于大盘转势初期" />
      <node TEXT="也就是说，2004年9月份以来只有600645叫龙头，其他的只叫超强势股" />
      <node TEXT="龙头只所以安全，就在于与大盘转势共振" />
      <node TEXT="市场也需要一只涨幅力度大的股票来树立赚钱效应" />
      <node TEXT="是我的一个短线介入点" />
    </node>
    <node TEXT="4.2 买入的方法" POSITION="right">
      <node TEXT="确认是追涨时，先进半仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓，让其利润最大化" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="让其利润最大化" />
      <node TEXT="当天不能涨停，次日择高点先出等回调做守株待兔" />
    </node>
    <node TEXT="4.3 买入的注意事项" POSITION="right">
      <node TEXT="我的追涨操作为什么都出现在大盘已大涨的情况下" />
      <node TEXT="原因很简单，我不能确认每一次大盘是否能继续向上，所以就挑最强的股票上" />
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
      <node TEXT="说白了，不参与任何性质整理！" />
      <node TEXT="任何一种操作方法，只要是参与了任何级别调整，买了不是为了马上挣钱，这种方法都不是短线" />
    </node>
  <node TEXT="第5章：持有与卖出策略" POSITION="right">
  </node>
    <node TEXT="5.1 持有策略" POSITION="right">
      <node TEXT="确认是追涨时，先进半仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="让其利润最大化" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓" />
    </node>
    <node TEXT="5.2 卖出" POSITION="right">
      <node TEXT="当天不能涨停，次日择高点先出等回调做守株待兔" />
      <node TEXT="让其利润最大化" />
      <node TEXT="但不要贪婪" />
      <node TEXT="龙头只所以安全，就在于与大盘转势共振" />
      <node TEXT="如果大盘明后天量能缩下来，那也只有操作600645才不会让人亏损" />
    </node>
    <node TEXT="5.3 卖出的方法" POSITION="right">
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="让其利润最大化" />
      <node TEXT="失利后止损不加仓" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓，失利后止损不加仓" />
      <node TEXT="龙头需要技术吗，不需要，要的是临阵时的果敢和勇气" />
    </node>
  <node TEXT="第6章：仓位管理与资金管理" POSITION="right">
  </node>
    <node TEXT="6.1 仓位管理的原则" POSITION="right">
      <node TEXT="确认是追涨时，先进半仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="让其利润最大化" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓" />
    </node>
    <node TEXT="6.2 仓位管理的方法" POSITION="right">
      <node TEXT="确认是追涨时，先进半仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="让其利润最大化" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓" />
    </node>
    <node TEXT="6.3 仓位管理的注意事项" POSITION="right">
      <node TEXT="确认是追涨时，先进半仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓" />
      <node TEXT="失利后止损不加仓" />
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
    </node>
  <node TEXT="第7章：风险控制与资金管理" POSITION="right">
  </node>
    <node TEXT="7.1 风险控制的原则" POSITION="right">
      <node TEXT="失利后止损不加仓" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓，失利后止损不加仓" />
      <node TEXT="说白了，不参与任何性质整理！" />
      <node TEXT="任何一种操作方法，只要是参与了任何级别调整，买了不是为了马上挣钱，这种方法都不是短线" />
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
    </node>
    <node TEXT="7.2 风险控制的方法" POSITION="right">
      <node TEXT="失利后止损不加仓" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓，失利后止损不加仓" />
      <node TEXT="确认是追涨时，先进半仓" />
      <node TEXT="当天涨停，次日继续加仓到全仓" />
      <node TEXT="当天不能涨停，次日择高点先出等回调做守株待兔" />
    </node>
    <node TEXT="7.3 风险控制的注意事项" POSITION="right">
      <node TEXT="失利后止损不加仓" />
      <node TEXT="做守株待兔时，也是先半仓，获利后出局不加仓，失利后止损不加仓" />
      <node TEXT="让其利润最大化，但不要贪婪" />
      <node TEXT="到达目标位就要果断卖出" />
      <node TEXT="龙头需要技术吗，不需要，要的是临阵时的果敢和勇气" />
    </node>
  <node TEXT="第8章：心态管理与修身养性" POSITION="right">
  </node>
    <node TEXT="8.1 投资的心态" POSITION="right">
      <node TEXT="等待需要绝对的耐心" />
      <node TEXT="在一轮经典的下跌过后，市场面临转势，但我们不知道谁会先涨" />
      <node TEXT="一旦发现，需要经验来确认" />
      <node TEXT="跟随则是最次要的买入动作了" />
      <node TEXT="不要被市场情绪左右" />
    </node>
    <node TEXT="8.2 心态管理的方法" POSITION="right">
      <node TEXT="制定详细的投资计划" />
      <node TEXT="按计划执行，不要随意更改" />
      <node TEXT="严格执行止损纪律" />
      <node TEXT="纪律是保护本金的最后一道防线" />
      <node TEXT="定期反思总结" />
    </node>
    <node TEXT="8.3 心态管理的注意事项" POSITION="right">
      <node TEXT="市场情绪，不要被左右" />
      <node TEXT="冷静才能做出正确的决策" />
      <node TEXT="短期波动是正常的，不要被影响" />
      <node TEXT="只要趋势没有结束，就要持有" />
      <node TEXT="相信自己的判断" />
    </node>
  <node TEXT="第9章：短线节奏的把握" POSITION="right">
  </node>
    <node TEXT="9.1 短线节奏的重要性" POSITION="right">
      <node TEXT="超短线我最有发言权了，从1998年到2006年7月23日，资金从10几万到几千万" />
      <node TEXT="成交量从两三百万到7,8个亿" />
      <node TEXT="豪宅，名车，吃喝玩乐，通通从股市中来" />
    </node>
    <node TEXT="9.2 短线节奏的把握方法" POSITION="right">
      <node TEXT="需要绝对的耐心" />
      <node TEXT="在一轮经典的下跌过后，市场面临转势，但我们不知道谁会先涨" />
      <node TEXT="需要经验来确认" />
      <node TEXT="龙头需要技术吗，不需要，要的是临阵时的果敢和勇气" />
      <node TEXT="则是最次要的买入动作了" />
    </node>
    <node TEXT="9.3 短线节奏的注意事项" POSITION="right">
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
      <node TEXT="说白了，不参与任何性质整理！" />
      <node TEXT="说白了，不参与任何性质整理！" />
      <node TEXT="任何一种操作方法，只要是参与了任何级别调整，买了不是为了马上挣钱，这种方法都不是短线" />
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
    </node>
  <node TEXT="第10章：实战案例分析" POSITION="right">
  </node>
    <node TEXT="10.1 600645案例（2004年9月）" POSITION="right">
      <node TEXT="2004年9月份以来，600645是龙头" />
      <node TEXT="龙头只所以安全，就在于与大盘转势共振" />
      <node TEXT="市场也需要一只涨幅力度大的股票来树立赚钱效应" />
    </node>
    <node TEXT="10.2 000503案例（2004年11月）" POSITION="right">
      <node TEXT="2004年11月份以来，000503是超强势股" />
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
    </node>
    <node TEXT="10.3 新大陆案例（2003年）" POSITION="right">
      <node TEXT="新大陆第二波的推手" />
      <node TEXT="ASKING进入十大股东" />
      <node TEXT="龙头需要技术吗，不需要，要的是临阵时的果敢和勇气" />
      <node TEXT="如果你操作的一直都是市场各阶段最强的股票，那你自然就能做到龙头" />
    </node>
  <node TEXT="第11章：常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="11.1 误区一：频繁交易" POSITION="right">
      <node TEXT="频繁买卖，追求短期暴利" />
      <node TEXT="不愿意持有，拿不住股票" />
    </node>
    <node TEXT="11.2 误区二：参与调整" POSITION="right">
      <node TEXT="参与了任何级别调整，买了不是为了马上挣钱" />
      <node TEXT="说白了，参与任何性质整理！" />
    </node>
    <node TEXT="11.3 误区三：强做" POSITION="right">
      <node TEXT="不符合条件而去强做" />
      <node TEXT="我们赚大钱，全是符合这样的条件，而亏钱基本都是不符合而去强做" />
    </node>
    <node TEXT="11.4 误区四：重仓一只股票" POSITION="right">
      <node TEXT="把所有资金都投入一只股票" />
      <node TEXT="不注意分散风险" />
    </node>
    <node TEXT="11.5 误区五：不设止损" POSITION="right">
      <node TEXT="不设止损位，抱幻想" />
      <node TEXT="亏损后死扛，不愿意认错" />
    </node>
  <node TEXT="第12章：与其他游资的比较" POSITION="right">
  </node>
    <node TEXT="12.1 与炒股养家的比较" POSITION="right">
      <node TEXT="都注重市场情绪和人气" />
      <node TEXT="都有自己完整的交易体系" />
      <node TEXT="炒股养家更注重情绪周期，ASKING更注重龙头战法" />
      <node TEXT="炒股养家更稳健，ASKING更激进" />
    </node>
    <node TEXT="12.2 与职业炒手的比较" POSITION="right">
      <node TEXT="都擅长龙头战法" />
      <node TEXT="都注重选股" />
      <node TEXT="职业炒手更注重交易本质，ASKING更注重龙头战法" />
      <node TEXT="职业炒手更注重弱市操作，ASKING更注重超强势股" />
    </node>
    <node TEXT="12.3 与赵老哥的比较" POSITION="right">
      <node TEXT="都擅长龙头战法" />
      <node TEXT="都注重题材炒作" />
      <node TEXT="赵老哥更注重连板战法，ASKING更注重龙头战法" />
      <node TEXT="赵老哥更注重题材，ASKING更注重人气" />
    </node>
  <node TEXT="第13章：自我修炼与提升" POSITION="right">
  </node>
    <node TEXT="13.1 学习名家手法" POSITION="right">
      <node TEXT="ASKING在成长过程中，学习了不少名家的操盘手法" />
      <node TEXT="不断锤炼自己，才能快速进步" />
    </node>
    <node TEXT="13.2 建立自己的交易体系" POSITION="right">
      <node TEXT="ASKING建立了完整的龙头战法体系" />
      <node TEXT="这是他成功的关键" />
    </node>
    <node TEXT="13.3 不断自我否定" POSITION="right">
      <node TEXT="即使现在是大游资，不进则退" />
      <node TEXT="必须不断学习，不断进步" />
    </node>
    <node TEXT="13.4 做自己看的懂的" POSITION="right">
      <node TEXT="&gt; **我也只能理解很小一部分的市场，做自己看的懂的，赚自己模式的钱，只赚自己能力范围内看的懂的钱，这是股市生存之道。**" />
    </node>
  <node TEXT="第14章：总结与核心要点" POSITION="right">
  </node>
    <node TEXT="14.1 核心理念" POSITION="right">
      <node TEXT="1. **只做超强势股的追涨和守株待兔**
2. **等待需要绝对的耐心，发现需要经验来确认，跟随则是最次要的买入动作了**
3. **龙头需要技术吗，不需要，要的是临阵时的果敢和勇气**
4. **..." />
    </node>
    <node TEXT="14.2 选股体系" POSITION="right">
      <node TEXT="1. **选股的原则**：人气股、领涨股、龙头股；超强势股；与市场共振；不做下跌通道
2. **选股的方法**：等待；发现；跟随
3. **选股的注意事项**：不要强做；不要参与调整；不要做超强势股" />
    </node>
    <node TEXT="14.3 买入时机把握" POSITION="right">
      <node TEXT="1. **买入时机的选择**：大盘转势初期；与大盘共振；守株待兔；二次脉冲
2. **买入的方法**：半仓买入；全仓买入；守株待兔买入；龙头买入
3. **买入的注意事项**：不要追高；不要强做；不要..." />
    </node>
    <node TEXT="14.4 风险控制" POSITION="right">
      <node TEXT="1. **风险控制的原则**：止损是保护本金的最后一道防线；不要参与任何性质整理；不要强做；不要重仓一只股票
2. **风险控制的方法**：止损；半仓操作；守株待兔；龙头战法
3. **风险控制的注意..." />
    </node>
    <node TEXT="14.5 心态管理" POSITION="right">
      <node TEXT="1. **投资的心态**：耐心；纪律；冷静；自信
2. **心态管理的方法**：制定计划；执行纪律；反思总结；保持学习
3. **心态管理的注意事项**：不要被市场情绪左右；不要被短期波动影响；不要被..." />
    </node>
  <node TEXT="第15章：行动计划与自测题" POSITION="right">
  </node>
    <node TEXT="15.1 30天行动计划" POSITION="right">
      <node TEXT="[ ] 阅读ASKING的经典文章3遍" />
      <node TEXT="[ ] 理解"只做超强势股的追涨和守株待兔"的深刻含义" />
      <node TEXT="[ ] 总结自己过去投资的误区" />
      <node TEXT="[ ] 制定"不参与任何性质整理"的操作纪律" />
      <node TEXT="[ ] 深入研究选股的原则" />
    </node>
    <node TEXT="15.2 核心要点检查清单" POSITION="right">
      <node TEXT="[ ] 我是在做超强势股，还是在做普通股票？" />
      <node TEXT="[ ] 我理解龙头的本质吗？" />
      <node TEXT="[ ] 我是在等待，还是盲目操作？" />
      <node TEXT="[ ] 我是在做自己看的懂的，还是盲目操作？" />
      <node TEXT="[ ] 这是大盘转势初期吗？" />
    </node>
    <node TEXT="15.3 每日自测题" POSITION="right">
      <node TEXT="**基础题（必做）**：
1. ASKING的核心操作观念是什么？（答案：只做超强势股的追涨和守株待兔）
2. 龙头需要技术吗？（答案：不需要，要的是临阵时的果敢和勇气）
3. 我们赚大钱的条件是什么..." />
    </node>
  <node TEXT="附录：ASKING经典语录" POSITION="right">
    <node TEXT="1. **关于核心操作观念**：
   &gt; 只做超强势股的追涨和守株待兔（仓位管理必不可少，否则会做电梯）。" />
  </node>
</node>
</map>