<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="徐翔心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 81" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第一章：徐翔是谁？——从3万到40亿的私募一哥" POSITION="right">
  </node>
    <node TEXT="1.1 基本信息" POSITION="right">
      <node TEXT="**真名**：徐翔" />
      <node TEXT="**出生年代**：1976年" />
      <node TEXT="**炒股经历**：1993年（17岁）带3万入市" />
      <node TEXT="**资金成长**：从3万到40亿个人资产，管理规模70亿（泽熙投资）" />
      <node TEXT="**交易风格**：涨停板敢死队总舵主，快进快出，凶猛彪悍" />
    </node>
    <node TEXT="1.2 成长历程" POSITION="right">
      <node TEXT="| 时间段 | 资金规模 | 关键事件 |
|--------|------------|----------|
| 1993年 | 3万 | 17岁入市 |
| 1990年代末 | 不详 | 成为"..." />
    </node>
    <node TEXT="1.3 核心特点" POSITION="right">
      <node TEXT="1. **极致专注**：每天研究股市超过12小时，20年如一日
2. **快准狠**：涨停板敢死队风格，大进大出
3. **逆向思维**：别人贪婪我恐惧，别人恐惧我贪婪
4. **谨慎杠杆**：随着投..." />
    </node>
    <node TEXT="1.4 与炒股养家、Asking、独股一箭的对比" POSITION="right">
      <node TEXT="| 维度 | 炒股养家 | Asking | 独股一箭 | 徐翔 |
|------|----------|---------|------------|--------|
| **核心心法** | ..." />
    </node>
    <node TEXT="1.5 学习徐翔心法的意义" POSITION="right">
      <node TEXT="1. **掌握专注的力量**：唯有专注，才能保持警惕，才能在股市中存活
2. **理解长期投资**：长期投资不是持股周期长，而是投资生涯长
3. **学会逆向思维**：当市场观点高度一致时，拐点即将来..." />
    </node>
    <node TEXT="1.6 本章小结" POSITION="right">
      <node TEXT="专注是战胜市场的关键" />
      <node TEXT="长期投资是投资生涯长，不是持股周期长" />
      <node TEXT="逆向思维是超额收益的来源" />
      <node TEXT="谨慎使用杠杆" />
    </node>
  <node TEXT="第二章：徐翔的第一课——专注" POSITION="right">
  </node>
    <node TEXT="2.1 专注的含义" POSITION="right">
      <node TEXT="每天一早：晨会，研究员汇报" />
      <node TEXT="开盘后：进入交易室，交易时间绝不离开盘面" />
      <node TEXT="中午：与卖方研究员共进午餐" />
      <node TEXT="下午：继续交易" />
      <node TEXT="收盘后：一到两场路演" />
    </node>
    <node TEXT="2.2 专注的表现" POSITION="right">
      <node TEXT="**徐翔的专注表现**：
1. **几乎没有娱乐和其他爱好**：股市里的苦行僧
2. **交易时间尽量不离开盘面**：日复一日
3. **晚上复盘和研究股票**：不断学习和进步" />
    </node>
    <node TEXT="2.3 专注的代价" POSITION="right">
      <node TEXT="过程会枯燥、艰苦、疲惫" />
      <node TEXT="几乎没有娱乐和爱好" />
      <node TEXT="需要极强的自律" />
      <node TEXT="想要获胜，这是必不可少的代价" />
      <node TEXT="唯有无与伦比的专注，才有超乎寻常的回报" />
    </node>
    <node TEXT="2.4 本章小结" POSITION="right">
      <node TEXT="专注需要付出代价（枯燥、艰苦、疲惫）" />
      <node TEXT="想要获胜，这是必不可少的代价" />
    </node>
  <node TEXT="第三章：徐翔的第二课——长期投资" POSITION="right">
  </node>
    <node TEXT="3.1 长期投资不是持股周期长" POSITION="right">
      <node TEXT="长期投资就是买入后持有很长时间（比如1年、2年、5年）" />
      <node TEXT="不考虑卖出，一直持有" />
      <node TEXT="长期投资不是持股周期长，而是**投资生涯长**" />
      <node TEXT="只有把投资当成终身事业来做，你的心态才会长期，行为才会理性" />
      <node TEXT="徐翔从1993年入市，到2015年已经22年" />
    </node>
    <node TEXT="3.2 长期投资的特征" POSITION="right">
      <node TEXT="**徐翔的长期投资特征**：
1. **找到合适的投资方法**：唯有无与伦比的专注，才有超乎寻常的回报
2. **长期坚持**：一朝一夕的坚持不是长期，20年如一日才是长期
3. **心态长期**：不..." />
    </node>
    <node TEXT="3.3 长期投资的误区" POSITION="right">
      <node TEXT="**纠正**：长期投资是投资生涯长，不是持股周期长" />
      <node TEXT="**纠正**：长期投资也要止损，止损是保护利润" />
      <node TEXT="**纠正**：长期投资也要关注短期波动，以便找到更好的买点和卖点" />
    </node>
    <node TEXT="3.4 本章小结" POSITION="right">
      <node TEXT="长期投资是投资生涯长，不是持股周期长" />
      <node TEXT="把投资当成终身事业" />
    </node>
  <node TEXT="第四章：徐翔的第三课——绝对收益和相对收益" POSITION="right">
  </node>
    <node TEXT="4.1 绝对收益 vs 相对收益" POSITION="right">
      <node TEXT="定义：不跑输大盘，不亏钱" />
      <node TEXT="目标：保住本金" />
      <node TEXT="方法：尽量回避风险" />
      <node TEXT="定义：跑赢大盘，超越指数" />
      <node TEXT="目标：获取超额收益" />
    </node>
    <node TEXT="4.2 徐翔的解决方案：绝对收益+相对收益" POSITION="right">
      <node TEXT="既要对公司基本面有深入的研究，以挑选标的" />
      <node TEXT="又要对市场情绪有敏感的体悟，以寻找买卖点" />
    </node>
    <node TEXT="4.3 绝对收益和相对收益的平衡" POSITION="right">
      <node TEXT="**先取绝对收益，再兼顾相对收益**" />
      <node TEXT="无论是哪种收益，都必须付出辛勤的劳动" />
    </node>
    <node TEXT="4.4 本章小结" POSITION="right">
      <node TEXT="绝对收益是基础，相对收益是目标" />
      <node TEXT="平衡两者需要付出辛勤的劳动" />
    </node>
  <node TEXT="第五章：徐翔的第四课——逆向思维" POSITION="right">
  </node>
    <node TEXT="5.1 逆向思维的含义" POSITION="right">
      <node TEXT="当研究员意见与市场的主流意见趋同时，被否定的概率就显著增加" />
      <node TEXT="当市场中最热门的板块和股票，总是特别警惕" />
      <node TEXT="当行情最火爆，涨停板满屏的时候，总是心生寒意" />
      <node TEXT="当市场的观点高度一致时，拐点也就即将来临了" />
    </node>
    <node TEXT="5.2 逆向思维的表现" POSITION="right">
      <node TEXT="**徐翔的逆向思维表现**：
1. **经常否定研究员意见**：当研究员意见与市场主流意见趋同时
2. **重仓股票在市场报告一片看好时悄悄出局**：卖出的价格屡屡是市场的阶段顶部
3. **警惕最热..." />
    </node>
    <node TEXT="5.3 逆向思维的代价" POSITION="right">
      <node TEXT="经常错过机会（当市场一致看好时，你警惕，结果继续涨）" />
      <node TEXT="经常买在半山腰（当市场一致看空时，你贪婪，结果继续跌）" />
      <node TEXT="克服人性的弱点，需要长时间的磨练" />
      <node TEXT="逆向思维是超额收益的来源" />
    </node>
    <node TEXT="5.4 本章小结" POSITION="right">
      <node TEXT="逆向思维需要长时间磨练" />
      <node TEXT="知易行难，克服人性的弱点" />
    </node>
  <node TEXT="第六章：徐翔的第五课——谨慎使用杠杆" POSITION="right">
  </node>
    <node TEXT="6.1 杠杆的成本和风险" POSITION="right">
      <node TEXT="杠杆有成本（利息、手续费等）" />
      <node TEXT="杠杆有期限（必须在一定时间内归还）" />
      <node TEXT="杠杆会使投资行为发生扭曲" />
      <node TEXT="在成本、期限和平仓的压力下，投资者要么变得更加激进，希望尽快赚取更多的利润，导致冒了更大的风险" />
      <node TEXT="要么变得更加保守，害怕因为下跌而导致平仓，从而失去一些投资机会" />
    </node>
    <node TEXT="6.2 徐翔对杠杆的态度" POSITION="right">
      <node TEXT="徐翔对杠杆并不陌生（涨停板敢死队经常使用杠杆）" />
      <node TEXT="但随着投资时间越长，他对杠杆的态度越发谨慎" />
      <node TEXT="2014年以来，随着市场的转暖，许多投资者眼见暴利在前，纷纷加杠杆" />
      <node TEXT="但是，徐翔却没有加杠杆" />
      <node TEXT="相反，泽熙在2014年底大比例分红，将本已永远封闭的产品规模继续降了许多" />
    </node>
    <node TEXT="6.3 杠杆的案例：昌九生化" POSITION="right">
      <node TEXT="有多少投资人因为加了杠杆，一夜之间血本无归" />
      <node TEXT="即使股价之后反弹，也因为被强行平仓而错失纠错机会" />
      <node TEXT="**杠杆的代价就是，哪怕你成功99次，最后一次失败就足以让你回到起点，甚至连翻本机会也丧失**" />
      <node TEXT="他自己也曾经用过杠杆，有过暴利的经历，更有过惨痛的教训" />
      <node TEXT="现在，他想他不会再愿意尝试这把锋利的双刃剑了" />
    </node>
    <node TEXT="6.4 本章小结" POSITION="right">
      <node TEXT="随着投资时间越长，对杠杆越谨慎" />
      <node TEXT="杠杆有成本和风险" />
    </node>
  <node TEXT="第七章：徐翔的第六课——股价有时与基本面无关" POSITION="right">
  </node>
    <node TEXT="7.1 重庆啤酒案例" POSITION="right">
      <node TEXT="2012年初，重庆啤酒发布乙肝疫苗临床揭盲结果" />
      <node TEXT="被寄予厚望的疫苗居然基本无效" />
      <node TEXT="公告一出，股价从82元连续跌停" />
      <node TEXT="在股价跌至28元的那天，奇迹发生了" />
      <node TEXT="巨量买盘一开盘就横扫千军，股价扶摇直上，盘中一度涨停" />
    </node>
    <node TEXT="7.2 徐翔的解释："重庆啤酒不是股票，是彩票"" POSITION="right">
      <node TEXT="股价有时与基本面无关" />
      <node TEXT="股价只跟群众的心理相关" />
    </node>
    <node TEXT="7.3 启示：股市是多维度的" POSITION="right">
      <node TEXT="股价是基本面的反映" />
      <node TEXT="基本面好，股价就涨；基本面差，股价就跌" />
      <node TEXT="股市是多维度的，基本面只是其中的一维" />
      <node TEXT="正如巴菲特所说，股市长期是称重机，但短期是投票机" />
      <node TEXT="一个精明的投资人，既可以用扎实的基本面研究赚钱，也可以用精准的心理学赚钱" />
    </node>
    <node TEXT="7.4 本章小结" POSITION="right">
      <node TEXT="不要迷信基本面" />
      <node TEXT="股价有时与基本面无关" />
    </node>
  <node TEXT="第八章：徐翔的第七课——不要被黑天鹅打倒" POSITION="right">
  </node>
    <node TEXT="8.1 黑天鹅事件：酒鬼酒案例" POSITION="right">
      <node TEXT="大约在40元的时候，泽熙重仓酒鬼酒" />
      <node TEXT="但黑天鹅不期而至，塑化剂事件爆发了" />
      <node TEXT="停牌，复牌，连续跌停，最低27元" />
      <node TEXT="损失惨重" />
      <node TEXT="泽熙产品的净值受此影响大约回撤了0.1元" />
    </node>
    <node TEXT="8.2 如何应对黑天鹅？" POSITION="right">
      <node TEXT="碰到这样的情况，能够第一时间斩仓的已然不多" />
      <node TEXT="斩仓后还能抄底成功反败为胜者更是寥寥" />
      <node TEXT="**钢铁一样的神经**：没有钢铁一样的神经，很难做到这一点" />
      <node TEXT="**冷静认赔**：在失误面前，怨天尤人无济于事，做缩头乌龟也于事无补" />
      <node TEXT="**勇敢面对**：冷静，然后勇敢地面对，直至重新踏上正确的轨道，并把教训变成未来的财富" />
    </node>
    <node TEXT="8.3 黑天鹅的必然性" POSITION="right">
      <node TEXT="股市总是不缺乏黑天鹅事件" />
      <node TEXT="长期而言，想要完全规避黑天鹅是不可能任务" />
      <node TEXT="有人被黑天鹅击倒了一蹶不振" />
      <node TEXT="有人在黑天鹅来临时面不改色，冷静认赔，同时还在寻找反击的机会" />
    </node>
    <node TEXT="8.4 本章小结" POSITION="right">
      <node TEXT="不要被黑天鹅打倒" />
      <node TEXT="冷静面对，勇敢反击" />
    </node>
  <node TEXT="第九章：徐翔的交易风格——涨停板敢死队" POSITION="right">
  </node>
    <node TEXT="9.1 涨停板敢死队的核心" POSITION="right">
      <node TEXT="大进大出，高起高落" />
      <node TEXT="快进快出，凶猛彪悍" />
    </node>
    <node TEXT="9.2 涨停板敢死队的选股" POSITION="right">
      <node TEXT="**选股标准**：
1. **有热点题材**：没有热点题材的股票不做
2. **有涨停板**：没有涨停板的股票不做
3. **是龙头股**：跟风股不做，只做龙头股" />
    </node>
    <node TEXT="9.3 涨停板敢死队的买点" POSITION="right">
      <node TEXT="**敢于追涨停板**：涨停板不是风险，而是机会" />
      <node TEXT="**快进快出**：今天涨停，明天就卖" />
    </node>
    <node TEXT="9.4 涨停板敢死队的卖点" POSITION="right">
      <node TEXT="**有赚就跑**：不追求卖在最高点" />
      <node TEXT="**快进快出**：今天买，明天就卖" />
    </node>
    <node TEXT="9.5 本章小结" POSITION="right">
      <node TEXT="涨停板不是风险，而是机会" />
      <node TEXT="快进快出，凶猛彪悍" />
    </node>
  <node TEXT="第十章：徐翔的情绪控制——钢铁一样的神经" POSITION="right">
  </node>
    <node TEXT="10.1 情绪控制的核心" POSITION="right">
      <node TEXT="**钢铁一样的神经**：没有钢铁一样的神经，很难做到在酒鬼酒跌停时抄底，然后反弹时卖出" />
      <node TEXT="**冷静面对**：在失误面前，怨天尤人无济于事，做缩头乌龟也于事无补" />
      <node TEXT="**勇敢反击**：冷静，然后勇敢地面对，直至重新踏上正确的轨道" />
    </node>
    <node TEXT="10.2 情绪控制的技巧" POSITION="right">
      <node TEXT="**徐翔的情绪控制技巧**：
1. **专注**：每天研究股市超过12小时，没有时间情绪失控
2. **长期主义**：把投资当成终身事业，不追求短期暴利
3. **逆向思维**：别人贪婪我恐惧，别人恐..." />
    </node>
    <node TEXT="10.3 情绪失控的案例" POSITION="right">
      <node TEXT="酒鬼酒塑化剂事件爆发，股价连续跌停" />
      <node TEXT="普通投资者：情绪失控，怨天尤人，做缩头乌龟" />
      <node TEXT="徐翔：钢铁一样的神经，冷静认赔，勇敢抄底，然后反弹时卖出" />
      <node TEXT="情绪失控是交易的大敌" />
      <node TEXT="只有控制情绪，才能冷静面对市场" />
    </node>
    <node TEXT="10.4 本章小结" POSITION="right">
      <node TEXT="情绪失控是交易的大敌" />
      <node TEXT="只有控制情绪，才能冷静面对市场" />
    </node>
  <node TEXT="第十一章：徐翔的风险控制——谨慎杠杆、严格止损" POSITION="right">
  </node>
    <node TEXT="11.1 风险控制的核心" POSITION="right">
      <node TEXT="**徐翔的风险控制**：
1. **谨慎使用杠杆**：随着投资时间越长，对杠杆越谨慎
2. **严格止损**：买入后不能下跌超过10%，否则无条件止损，不允许补仓
3. **绝对收益为基础**：先取绝..." />
    </node>
    <node TEXT="11.2 风险控制的技巧" POSITION="right">
      <node TEXT="**徐翔的风险控制技巧**：
1. **谨慎使用杠杆**：杠杆是双刃剑，慎用
2. **严格止损**：跌破止损位就割肉，不犹豫，不幻想
3. **分散持仓**：不要满仓一只股票，分散风险" />
    </node>
    <node TEXT="11.3 风险失控的案例" POSITION="right">
      <node TEXT="昌九生化：有多少投资人因为加了杠杆，一夜之间血本无归" />
      <node TEXT="即使股价之后反弹，也因为被强行平仓而错失纠错机会" />
      <node TEXT="杠杆的代价就是，哪怕你成功99次，最后一次失败就足以让你回到起点" />
      <node TEXT="风险控制是交易成功的关键" />
      <node TEXT="杠杆是双刃剑，慎用" />
    </node>
    <node TEXT="11.4 本章小结" POSITION="right">
      <node TEXT="保住本金是投资的第一原则" />
      <node TEXT="杠杆是双刃剑，慎用" />
    </node>
  <node TEXT="第十二章：徐翔的心态修炼——专注、长期主义、逆向思维" POSITION="right">
  </node>
    <node TEXT="12.1 心态修炼的核心" POSITION="right">
      <node TEXT="**徐翔的心态修炼**：
1. **专注**：每天研究股市超过12小时，20年如一日
2. **长期主义**：把投资当成终身事业，不追求短期暴利
3. **逆向思维**：别人贪婪我恐惧，别人恐惧我贪婪" />
    </node>
    <node TEXT="12.2 心态修炼的技巧" POSITION="right">
      <node TEXT="**徐翔的心态修炼技巧**：
1. **专注**：把投资当成终身事业，不断学习和进步
2. **长期主义**：设定长期的投资目标，不追求短期暴利
3. **逆向思维**：独立思考，不要人云亦云" />
    </node>
    <node TEXT="12.3 心态崩溃的案例" POSITION="right">
      <node TEXT="徐翔在酒鬼酒塑化剂事件爆发后，净值回撤了0.1元" />
      <node TEXT="普通投资者：心态崩溃，怨天尤人，做缩头乌龟" />
      <node TEXT="徐翔：心态平稳，冷静认赔，勇敢抄底，然后反弹时卖出，不到一个月便重新创新高" />
      <node TEXT="心态是交易成功的关键" />
      <node TEXT="只有好心态，才能冷静面对市场" />
    </node>
    <node TEXT="12.4 本章小结" POSITION="right">
      <node TEXT="心态是交易成功的关键" />
      <node TEXT="专注、长期主义、逆向思维" />
    </node>
  <node TEXT="第十三章：从徐翔心法到自己的交易系统" POSITION="right">
  </node>
    <node TEXT="13.1 徐翔心法的核心要点回顾" POSITION="right">
      <node TEXT="1. **专注**：每天研究股市超过12小时，20年如一日
2. **长期投资**：长期投资是投资生涯长，不是持股周期长
3. **绝对收益+相对收益**：先取绝对收益，再兼顾相对收益
4. **逆向..." />
    </node>
    <node TEXT="13.2 如何将这些要点融入自己的交易系统？" POSITION="right">
      <node TEXT="我的专注度如何？" />
      <node TEXT="我是否有长期投资目标？" />
      <node TEXT="我更看重绝对收益还是相对收益？" />
      <node TEXT="我是否有逆向思维？" />
      <node TEXT="我是否使用杠杆？" />
    </node>
    <node TEXT="13.3 建立自己的交易系统的步骤" POSITION="right">
      <node TEXT="我为什么要交易？" />
      <node TEXT="我的交易目标是什么？" />
      <node TEXT="我的交易风格是什么？" />
      <node TEXT="选股规则" />
      <node TEXT="买点规则" />
    </node>
    <node TEXT="13.4 本章小结" POSITION="right">
      <node TEXT="徐翔心法不是教条，而是启示" />
      <node TEXT="建立自己的交易系统，才是最重要的" />
    </node>
  <node TEXT="第十四章：徐翔心法的常见误区" POSITION="right">
  </node>
    <node TEXT="14.1 误区一：徐翔的成功只是依靠内幕" POSITION="right">
      <node TEXT="徐翔的成功只是依靠内幕交易" />
      <node TEXT="忽视了徐翔的专注、勤奋、投资哲学" />
      <node TEXT="徐翔的成功不仅仅是内幕交易，更是20年的专注和勤奋" />
      <node TEXT="如果你是高手，很多事情都会主动找到你，除去自己的贪婪，更有自己身不由己的一面" />
      <node TEXT="相信在更多人的眼里，徐是中国股市一个时代的闪耀之星" />
    </node>
    <node TEXT="14.2 误区二：涨停板敢死队就是追涨杀跌" POSITION="right">
      <node TEXT="涨停板敢死队就是追涨杀跌" />
      <node TEXT="没有技术含量" />
      <node TEXT="涨停板敢死队需要精准的选股、果断的买入、果断的卖出" />
      <node TEXT="不是所有的涨停板都追，只追龙头股、热点股" />
      <node TEXT="需要极高的情绪控制能力和风险控制能力" />
    </node>
    <node TEXT="14.3 误区三：徐翔心法可以快速致富" POSITION="right">
      <node TEXT="学习了徐翔心法，就能快速致富" />
      <node TEXT="忽视了学习和实践的过程" />
      <node TEXT="徐翔心法需要长期学习和实践" />
      <node TEXT="徐翔用了20年才达到今天的成就" />
      <node TEXT="快速致富是不现实的" />
    </node>
    <node TEXT="14.4 误区四：谨慎杠杆就是不要使用杠杆" POSITION="right">
      <node TEXT="谨慎杠杆就是不要使用杠杆" />
      <node TEXT="杠杆是坏事" />
      <node TEXT="谨慎杠杆不是不要使用杠杆，而是要慎用" />
      <node TEXT="在有机会的时候，可以使用杠杆" />
      <node TEXT="但要控制杠杆比例，设置止损" />
    </node>
    <node TEXT="14.5 本章小结" POSITION="right">
      <node TEXT="理解徐翔心法的精髓" />
      <node TEXT="避免常见误区" />
    </node>
  <node TEXT="第十五章：总结与行动计划" POSITION="right">
  </node>
    <node TEXT="15.1 徐翔心法核心要点总结" POSITION="right">
      <node TEXT="1. **专注**：每天研究股市超过12小时，20年如一日
2. **长期投资**：长期投资是投资生涯长，不是持股周期长
3. **绝对收益+相对收益**：先取绝对收益，再兼顾相对收益
4. **逆向..." />
    </node>
    <node TEXT="15.2 行动计划" POSITION="right">
      <node TEXT="Week 1-2：理论学习，理解徐翔心法的核心要点" />
      <node TEXT="Week 3-4：模拟盘练习，实践徐翔心法" />
      <node TEXT="Week 1-2：小资金实盘，验证徐翔心法" />
      <node TEXT="Week 3-4：继续实盘，不断复盘和改进" />
      <node TEXT="逐步加大资金" />
    </node>
    <node TEXT="15.3 核心提醒" POSITION="right">
      <node TEXT="理解精髓，不要死记硬背" />
      <node TEXT="结合自己的情况，灵活运用" />
      <node TEXT="不要盲目模仿" />
      <node TEXT="建立适合自己的交易系统" />
      <node TEXT="交易是一场马拉松" />
    </node>
    <node TEXT="15.4 学习资源推荐" POSITION="right">
      <node TEXT="《股票大作手回忆录》" />
      <node TEXT="《海龟交易法则》" />
      <node TEXT="《通向财务自由之路》" />
      <node TEXT="淘股吧" />
      <node TEXT="雪球" />
    </node>
    <node TEXT="15.5 结语" POSITION="right">
      <node TEXT="**专注是战胜市场的关键**" />
      <node TEXT="**长期投资是投资生涯长，不是持股周期长**" />
      <node TEXT="**建立自己的交易系统，才是最重要的**" />
    </node>
  <node TEXT="附录：徐翔经典语录" POSITION="right">
    <node TEXT="创建时间：2026-06-08" />
    <node TEXT="版本：v1.0" />
    <node TEXT="作者：WorkBuddy AI" />
    <node TEXT="适用对象：所有投资者（建议有经验后学习）" />
    <node TEXT="预计学习周期：8-10周" />
  </node>
</node>
</map>