<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="92科比心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 91" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第1章：92科比简介与成长历程" POSITION="right">
  </node>
    <node TEXT="1.1 个人背景" POSITION="right">
      <node TEXT="**身份**：新生代首板高手" />
      <node TEXT="**参赛成绩**：半年度实盘赛第三名" />
      <node TEXT="和前两名的差距微弱" />
      <node TEXT="再给两个交易日时间，就能反超" />
      <node TEXT="**交易特点**：模式不固定，灵活多变" />
    </node>
    <node TEXT="1.2 交易模式多样性" POSITION="right">
      <node TEXT="低吸" />
      <node TEXT="追涨" />
      <node TEXT="打板" />
      <node TEXT="做首板" />
      <node TEXT="做1进2" />
    </node>
    <node TEXT="1.3 投资哲学" POSITION="right">
      <node TEXT="&gt; "真正的悟道，绝对不是仅仅限制于某种手法的操作。这是一种初级盈利的玩家的阶段。那么如果要晋级，做到大道无形，买入即是赚钱的点。"" />
    </node>
    <node TEXT="1.4 核心启示" POSITION="right">
      <node TEXT="半年度实盘赛第三名" />
      <node TEXT="模式不固定，灵活多变" />
      <node TEXT="大道无形的境界" />
      <node TEXT="买入即是赚钱的点" />
    </node>
  <node TEXT="第2章：大道无形的交易理念" POSITION="right">
  </node>
    <node TEXT="2.1 悟道的三个阶段" POSITION="right">
      <node TEXT="**特点**：限制于某种手法的操作" />
      <node TEXT="**表现**：只会一种或几种固定模式" />
      <node TEXT="**局限**：无法适应市场变化" />
      <node TEXT="**特点**：买入即是赚钱的点" />
      <node TEXT="**表现**：不局限于某种手法" />
    </node>
    <node TEXT="2.2 大道无形的基础能力" POSITION="right">
      <node TEXT="**短线情绪周期**：分为四个阶段" />
      <node TEXT="**定义**：你认为的这个故事能讲多大，能不能持续" />
      <node TEXT="**重要性**：影响着你做龙头的坚决程度" />
      <node TEXT="**培养方法**：" />
      <node TEXT="要有足够的信息渠道" />
    </node>
    <node TEXT="2.3 股票的本质理解" POSITION="right">
      <node TEXT="看透本质唯一做法：只能在接力的时候，一定要看这个故事是否有更多的人来接盘" />
      <node TEXT="股票股票，本质就是讲故事，然后卖给信故事的人" />
      <node TEXT="小资金讲小故事，大资金讲大故事" />
      <node TEXT="有的周期短，有的周期长而已" />
      <node TEXT="本质没有多大区别" />
    </node>
    <node TEXT="2.4 核心要点总结" POSITION="right">
      <node TEXT="1. 悟道不是限制于某种手法
2. 大道无形：买入即是赚钱的点
3. 基础能力：情绪周期理解 + 题材预判能力
4. 股票本质：筹码交换的游戏
5. 短线核心：人气带来的流动性溢价" />
    </node>
  <node TEXT="第3章：情绪周期四阶段理论" POSITION="right">
  </node>
    <node TEXT="3.1 四个阶段详解" POSITION="right">
      <node TEXT="**特点**：接着前面一个主跌的亏钱阶段" />
      <node TEXT="**策略**：低位试错，要有一定的勇气" />
      <node TEXT="**时机**：一般龙头见顶杀高位的阶段，往往是最好的布局低位新题材的时机" />
      <node TEXT="**模式**：高低切模式" />
      <node TEXT="轴研科技：2板切入，吃了4个板" />
    </node>
    <node TEXT="3.2 周期循环" POSITION="right">
      <node TEXT="**完整循环**：低位震荡 → 主升 → 高位震荡 → 主跌 → 低位震荡" />
    </node>
    <node TEXT="3.3 不同阶段的策略选择" POSITION="right">
      <node TEXT="| 阶段 | 特点 | 策略 | 仓位 |
|------|------|------|------|
| **低位震荡** | 试错期 | 布局低位新题材 | 轻仓试错 |
| **主升** | 利..." />
    </node>
    <node TEXT="3.4 核心要点总结" POSITION="right">
      <node TEXT="1. 情绪周期分为四个阶段
2. 低位震荡是试错期，要有勇气
3. 主升阶段大胆在分歧时介入
4. 高位震荡不建议博弈穿越
5. 主跌阶段第二天尾盘找买点
6. 第三天肯定会有情绪修复" />
    </node>
  <node TEXT="第4章：题材预判能力培养" POSITION="right">
  </node>
    <node TEXT="4.1 题材预判的重要性" POSITION="right">
      <node TEXT="**影响**：影响着你做龙头的坚决程度" />
      <node TEXT="**关键**：你认为的这个故事能讲多大，能不能持续" />
      <node TEXT="**基础**：买入之后，还能否持续" />
    </node>
    <node TEXT="4.2 认识过深 vs 认识过浅" POSITION="right">
      <node TEXT="**表现**：容易套住不走" />
      <node TEXT="**结果**：最终亏损" />
      <node TEXT="**原因**：对题材理解过深，不肯止损" />
      <node TEXT="**表现**：非常容易错失龙头" />
      <node TEXT="**结果**：踏空" />
    </node>
    <node TEXT="4.3 如何预判题材" POSITION="right">
      <node TEXT="要有足够的信息渠道" />
      <node TEXT="关注新闻" />
      <node TEXT="找完新闻，找相关个股" />
      <node TEXT="看该股各个方面综合筛选，盘子大小等等" />
      <node TEXT="大量无用信息去过滤" />
    </node>
    <node TEXT="4.4 先于市场发现可发酵的舆论事件" POSITION="right">
      <node TEXT="高效赚钱模式" />
      <node TEXT="需要敏锐的新闻敏感度" />
      <node TEXT="需要大量的信息过滤能力" />
      <node TEXT="需要判断市场是否会发酵" />
    </node>
    <node TEXT="4.5 核心要点总结" POSITION="right">
      <node TEXT="1. 题材预判影响做龙头的坚决程度
2. 认识过深容易套住，认识过浅容易错失
3. 预判题材需要三步：信息渠道 → 过滤信息 → 判断发酵程度
4. 先于市场发现可发酵的舆论事件是高效率钱模式
5. ..." />
    </node>
  <node TEXT="第5章：首板战法技巧" POSITION="right">
  </node>
    <node TEXT="5.1 92科比的首板理念" POSITION="right">
      <node TEXT="**模式多样**：做首板，做1进2，做龙头，低吸科创，低吸龙头" />
      <node TEXT="**不打板**：现在打首板不好打，因为AI太强大了，抢筹码太快" />
    </node>
    <node TEXT="5.2 首板技巧" POSITION="right">
      <node TEXT="要自己去关注" />
      <node TEXT="找完新闻，找相关个股" />
      <node TEXT="看该股各个方面综合筛选，盘子大小等等" />
      <node TEXT="有没有人气" />
      <node TEXT="人气会让他反包" />
    </node>
    <node TEXT="5.3 首板的风险" POSITION="right">
      <node TEXT="**现在难打**：因为AI太强大了，抢筹码太快" />
      <node TEXT="**封不住**：然后就是首板封不住" />
      <node TEXT="**没有溢价**：慢慢的三板没溢价，二板没溢价" />
    </node>
    <node TEXT="5.4 首板的时机选择" POSITION="right">
      <node TEXT="**低位试错期**：一般龙头见顶杀高位的阶段，往往是最好的布局低位新题材的时机" />
      <node TEXT="**情绪修复期**：主跌阶段第二天尾盘可以找买点" />
      <node TEXT="**新题材爆发期**：先于市场发现可发酵的舆论事件" />
    </node>
    <node TEXT="5.5 核心要点总结" POSITION="right">
      <node TEXT="1. 对新闻要有敏感度
2. 接力股关键看人气
3. 试错要积极
4. 现在首板不好打，AI抢筹码太快
5. 首板要从低位试错期、情绪修复期、新题材爆发期选择时机" />
    </node>
  <node TEXT="第6章：龙头战法精髓" POSITION="right">
  </node>
    <node TEXT="6.1 92科比的龙头理念" POSITION="right">
      <node TEXT="**介入方式**：不在乎是打板，还是低吸的。看好，分歧，买入。" />
      <node TEXT="**持有基础**：对题材深度，可发掘程度的预期" />
      <node TEXT="**卖出时机**：取决于你的预期，每个人预期不一样" />
    </node>
    <node TEXT="6.2 做龙头的关键" POSITION="right">
      <node TEXT="当市场都认为是龙头的时候，你就买就行了" />
      <node TEXT="龙头的命硬" />
      <node TEXT="需要参与龙头股，可以小仓位参与" />
      <node TEXT="积累经验" />
      <node TEXT="没有真实经验的积累，不行的" />
    </node>
    <node TEXT="6.3 龙头的持有与卖出" POSITION="right">
      <node TEXT="对题材深度，可发掘程度的预期" />
      <node TEXT="你觉得这个题材的故事还能讲，要敢于大胆的在分歧的时候介入" />
      <node TEXT="取决于你的预期，每个人预期不一样" />
      <node TEXT="卖点就不一样" />
      <node TEXT="朗姿为什么拿那么久：主要是看别人文章看激动上头了，然后也没什么可做的票" />
    </node>
    <node TEXT="6.4 龙头的命硬" POSITION="right">
      <node TEXT="龙头的命硬" />
      <node TEXT="朗姿为什么拿那么久" />
      <node TEXT="主要是看别人文章看激动上头了" />
    </node>
    <node TEXT="6.5 核心要点总结" POSITION="right">
      <node TEXT="1. 做龙头关键是'脖子'硬
2. 市场都认为是龙头的时候，你就买就行了
3. 参与龙头需要体验，小仓位参与，积累经验
4. 持有基础是对题材深度的预期
5. 卖出时机取决于你的预期" />
    </node>
  <node TEXT="第7章：补涨与切换战术" POSITION="right">
  </node>
    <node TEXT="7.1 短线世界观" POSITION="right">
      <node TEXT="&gt; "短线世界观：龙头、补涨、切换（在里面不停的加东西去充沛它的内容）"" />
    </node>
    <node TEXT="7.2 补涨战术" POSITION="right">
      <node TEXT="什么时候做补涨" />
      <node TEXT="高位做，低位做" />
      <node TEXT="你要填满世界观" />
      <node TEXT="过去经验中他各个炒作的节奏，是怎么走出来的" />
      <node TEXT="你要去总结体会感悟" />
    </node>
    <node TEXT="7.3 切换战术" POSITION="right">
      <node TEXT="在其他主流题材出现亏钱效应的时候，做注册制次新股，合力会比较较强" />
      <node TEXT="去复盘看每一次，切换的实际点" />
      <node TEXT="比如仁东控股什么时候开始涨的" />
      <node TEXT="你要去理解没有参与过得，要试着去理解他" />
      <node TEXT="即使没有参与过，这样下一个龙头出来，你才能从上次龙头走出来的特点，从中感觉得出来这一次龙头" />
    </node>
    <node TEXT="7.4 要么做高，要么做低，中位股的风险较大" POSITION="right">
      <node TEXT="中位股不容易成功" />
      <node TEXT="做高位或低位" />
      <node TEXT="要么做切换，要做新的题材要有新闻做配合" />
      <node TEXT="同题材的中位股亏钱效应是很高的" />
    </node>
    <node TEXT="7.5 核心要点总结" POSITION="right">
      <node TEXT="1. 短线世界观：龙头、补涨、切换
2. 补涨时机：高位做，低位做
3. 切换分为两种：补涨和其他题材
4. 切换手法通常在市场分歧的时候做
5. 要么做高，要么做低，中位股的风险较大" />
    </node>
  <node TEXT="第8章：量价形态与记忆形成" POSITION="right">
  </node>
    <node TEXT="8.1 92科比的观点" POSITION="right">
      <node TEXT="&gt; "量价，形态，是没有固定的标准的，这些东西是靠大量的记忆形成的。"" />
    </node>
    <node TEXT="8.2 量价分析的核心" POSITION="right">
      <node TEXT="量价，形态，是没有固定的标准的" />
      <node TEXT="这些东西是靠大量的记忆形成的" />
      <node TEXT="需要大量的复盘和记忆" />
      <node TEXT="放量上涨" />
      <node TEXT="缩量下跌" />
    </node>
    <node TEXT="8.3 记忆形成的重要性" POSITION="right">
      <node TEXT="量价，形态，是没有固定的标准的" />
      <node TEXT="这些东西是靠大量的记忆形成的" />
      <node TEXT="需要大量的复盘和记忆" />
      <node TEXT="把过去几年龙头股去复盘总结" />
      <node TEXT="填满理解力" />
    </node>
    <node TEXT="8.4 核心要点总结" POSITION="right">
      <node TEXT="1. 量价，形态，是没有固定的标准的
2. 这些东西是靠大量的记忆形成的
3. 需要大量的复盘和记忆
4. 把过去几年龙头股去复盘总结
5. 填满理解力" />
    </node>
  <node TEXT="第9章：弱转强战法" POSITION="right">
  </node>
    <node TEXT="9.1 什么是弱转强" POSITION="right">
      <node TEXT="&gt; "烂板一般第二天竞价会很低，但是开盘后买盘很凶，溢价预期很低的股票，第二天表现优异，就是弱转强"" />
    </node>
    <node TEXT="9.2 弱转强的理想状态" POSITION="right">
      <node TEXT="竞价高开属于做盘的迹象太明显了" />
      <node TEXT="弱转强不是体现在竞价上，而是被买上去的" />
    </node>
    <node TEXT="9.3 弱转强的操作方式" POSITION="right">
      <node TEXT="&gt; "弱转强只能排板，因为是缩量的，容易买不到。"" />
    </node>
    <node TEXT="9.4 弱转强的卖点" POSITION="right">
      <node TEXT="弱转强第三天可能强转强" />
      <node TEXT="一般是卖点，因为很可能强转弱" />
    </node>
    <node TEXT="9.5 弱转强的注意事项" POSITION="right">
      <node TEXT="弱转强只能排板，因为是缩量的，容易买不到" />
      <node TEXT="弱转强不喜欢竞价高开" />
      <node TEXT="竞价高开属于做盘的迹象太明显了" />
      <node TEXT="弱转强不是体现在竞价上，而是被买上去的" />
    </node>
    <node TEXT="9.6 核心要点总结" POSITION="right">
      <node TEXT="1. 弱转强：烂板后第二天表现优异
2. 弱转强最好不要体现在竞价上
3. 弱转强只能排板，因为是缩量的，容易买不到
4. 弱转强第三天可能强转强，一般是卖点
5. 弱转强卖点取决于你的预期" />
    </node>
  <node TEXT="第10章：反包二板战术" POSITION="right">
  </node>
    <node TEXT="10.1 反包二板的定义" POSITION="right">
      <node TEXT="反包二板会给很多龙头造成确定性的气势" />
      <node TEXT="大资金都喜欢反包后第二个板去买" />
      <node TEXT="因为反包第一个板，第二天走得怎么样不知道，很可能被闷杀" />
      <node TEXT="所以再来一个板，安全度很高，大家愿意去做" />
    </node>
    <node TEXT="10.2 反包二板的操作逻辑" POSITION="right">
      <node TEXT="反包第一个板，第二天走得怎么样不知道，很可能被闷杀" />
      <node TEXT="所以再来一个板，安全度很高" />
      <node TEXT="大家愿意去做" />
    </node>
    <node TEXT="10.3 反包二板的适用场景" POSITION="right">
      <node TEXT="反包二板会给很多龙头造成确定性的气势" />
      <node TEXT="大资金都喜欢反包后第二个板去买" />
      <node TEXT="因为安全度很高" />
    </node>
    <node TEXT="10.4 核心要点总结" POSITION="right">
      <node TEXT="1. 反包二板会给很多龙头造成确定性的气势
2. 大资金都喜欢反包后第二个板去买
3. 因为反包第一个板，第二天可能被闷杀
4. 再来一个板，安全度很高
5. 大家愿意去做" />
    </node>
  <node TEXT="第11章：风险控制与资金管理" POSITION="right">
  </node>
    <node TEXT="11.1 92科比的风险控制理念" POSITION="right">
      <node TEXT="小资金做大需要稳定的成功率" />
      <node TEXT="如果像你全部重仓做一只票，你的模式是不稳定的，容易大赚大亏" />
      <node TEXT="理想论坛每次比赛冠军都是长期做出来的，不是靠运气，是靠稳定的模式，靠复利做出来" />
      <node TEXT="没有自己的方法，一个亿的资金去做也是韭菜" />
    </node>
    <node TEXT="11.2 止损的重要性" POSITION="right">
      <node TEXT="不少朋友对投机本质意识不清楚的" />
      <node TEXT="都是高位信了中远海控，信了天齐锂业，信了军工，信了诸多吹大故事的逻辑" />
      <node TEXT="最终由于不止损，一波的回撤，是相当大的" />
      <node TEXT="甚至，不少人拿的杠杆做的趋势，都有爆仓的风险" />
    </node>
    <node TEXT="11.3 仓位管理" POSITION="right">
      <node TEXT="小资金也要分仓，也不加杠杆" />
      <node TEXT="做股票是长期活动，不能把账户压在一只票上" />
      <node TEXT="小资金做大需要稳定的成功率" />
      <node TEXT="不能把账户压在一只票上" />
      <node TEXT="小资金做大需要稳定的成功率" />
    </node>
    <node TEXT="11.4 核心要点总结" POSITION="right">
      <node TEXT="1. 小资金也要分仓，也不加杠杆
2. 做短线就是不断自我否定，不断修正自己
3. 对于已经淘汰的题材，反弹就赶紧走
4. 一旦不达预期就是走人，必须要杀伐果断
5. 小资金做大需要稳定的成功率" />
    </node>
  <node TEXT="第12章：心态管理与自我修正" POSITION="right">
  </node>
    <node TEXT="12.1 92科比的心态理念" POSITION="right">
      <node TEXT="#### 做短线就是不断自我否定，不断修正自己的地方
&gt; "做短线就是不断自我否定，不断修正自己的地方。"" />
    </node>
    <node TEXT="12.2 悟道的标准" POSITION="right">
      <node TEXT="&gt; "你长期做股票，你发现收益曲线稳定了，三到六个月，关键在于稳定，做股票不要追捧梭哈一个票，如果赚了容易让自己狂妄，买别的票你也容易梭哈其他票，所以短线选手要明白赚钱是行情给与的，不要重仓去赌..." />
    </node>
    <node TEXT="12.3 不要梭哈" POSITION="right">
      <node TEXT="如果赚了容易让自己狂妄" />
      <node TEXT="买别的票你也容易梭哈其他票" />
      <node TEXT="短线选手要明白赚钱是行情给与的" />
      <node TEXT="不要重仓去赌" />
      <node TEXT="很多人一输就没有赌的资本了" />
    </node>
    <node TEXT="12.4 做短线需要天赋和理解力" POSITION="right">
      <node TEXT="&gt; "做短线需要天赋和理解力的，做短线要做出来：首先模式是对的，天天换模式是不行的，要不断修正调整自己，做股票好的人总能够找到规律，善于总结"" />
    </node>
    <node TEXT="12.5 核心要点总结" POSITION="right">
      <node TEXT="1. 做短线就是不断自我否定，不断修正自己
2. 悟道的标准是收益曲线稳定三到六个月
3. 不要梭哈，梭哈大亏会让你心态崩了
4. 做短线需要天赋和理解力
5. 做股票好的人总能够找到规律，善于总结" />
    </node>
  <node TEXT="第13章：实战案例分析" POSITION="right">
  </node>
    <node TEXT="13.1 案例一：轴研科技（高低切模式）" POSITION="right">
      <node TEXT="**操作**：2板切入" />
      <node TEXT="**收益**：吃了4个板" />
      <node TEXT="**模式**：高低切模式" />
      <node TEXT="**成功关键**：" />
      <node TEXT="低位试错" />
    </node>
    <node TEXT="13.2 案例二：宏润建设（高低切模式）" POSITION="right">
      <node TEXT="**操作**：3板隔夜顶的一字" />
      <node TEXT="**收益**：也吃了4个板" />
      <node TEXT="**模式**：高低切模式" />
      <node TEXT="**成功关键**：" />
      <node TEXT="敢于顶一字" />
    </node>
    <node TEXT="13.3 案例三：星期六（主升阶段）" POSITION="right">
      <node TEXT="**操作**：主升阶段介入" />
      <node TEXT="**模式**：龙头战法" />
      <node TEXT="**成功关键**：" />
      <node TEXT="敢于大胆的在分歧的时候介入" />
      <node TEXT="对题材深度有预期" />
    </node>
    <node TEXT="13.4 案例四：省广集团（主升阶段）" POSITION="right">
      <node TEXT="**操作**：主升阶段介入" />
      <node TEXT="**模式**：龙头战法" />
      <node TEXT="**成功关键**：" />
      <node TEXT="敢于大胆的在分歧的时候介入" />
      <node TEXT="对题材深度有预期" />
    </node>
    <node TEXT="13.5 案例五：王府井（主升阶段）" POSITION="right">
      <node TEXT="**操作**：主升阶段介入" />
      <node TEXT="**模式**：龙头战法" />
      <node TEXT="**成功关键**：" />
      <node TEXT="敢于大胆的在分歧的时候介入" />
      <node TEXT="对题材深度有预期" />
    </node>
    <node TEXT="13.6 核心要点总结" POSITION="right">
      <node TEXT="1. 轴研科技：2板切入，吃了4个板
2. 宏润建设：3板隔夜顶的一字，吃了4个板
3. 星期六、省广集团、王府井：主升阶段介入
4. 成功关键：敢于在分歧时介入，对题材深度有预期
5. 模式：高低切..." />
    </node>
  <node TEXT="第14章：常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="14.1 误区一：认为悟道就是限制于某种手法" POSITION="right">
      <node TEXT="**错误理解**：悟道就是限制于某种手法的操作" />
      <node TEXT="**正确理解**：" />
      <node TEXT="真正的悟道，绝对不是仅仅限制于某种手法的操作" />
      <node TEXT="这是一种初级盈利的玩家的阶段" />
      <node TEXT="如果要晋级，做到大道无形，买入即是赚钱的点" />
    </node>
    <node TEXT="14.2 误区二：量价，形态，有固定的标准" POSITION="right">
      <node TEXT="**错误理解**：量价，形态，有固定的标准" />
      <node TEXT="**正确理解**：" />
      <node TEXT="量价，形态，是没有固定的标准的" />
      <node TEXT="这些东西是靠大量的记忆形成的" />
    </node>
    <node TEXT="14.3 误区三：盲目追高" POSITION="right">
      <node TEXT="**错误表现**：不判断市场情绪，盲目追高" />
      <node TEXT="**正确做法**：" />
      <node TEXT="不可追太高" />
      <node TEXT="除非市场情绪很好，龙头可追" />
    </node>
    <node TEXT="14.4 误区四：对于已经淘汰的题材，反弹不走" POSITION="right">
      <node TEXT="**错误表现**：对于已经淘汰的题材，反弹不走，在里面干等" />
      <node TEXT="**正确做法**：" />
      <node TEXT="对于已经淘汰的题材做短线，反弹就赶紧走" />
      <node TEXT="一旦不及预期的走势就赶紧割肉" />
      <node TEXT="因为超短就是做隔日，一旦不达预期就是走人" />
    </node>
    <node TEXT="14.5 误区五：梭哈一个票" POSITION="right">
      <node TEXT="**错误表现**：全部重仓做一只票" />
      <node TEXT="**正确做法**：" />
      <node TEXT="小资金也要分仓，也不加杠杆" />
      <node TEXT="做股票是长期活动，不能把账户压在一只票上" />
      <node TEXT="反对梭哈，梭哈大亏会让你心态崩了" />
    </node>
    <node TEXT="14.6 核心要点总结" POSITION="right">
      <node TEXT="1. 悟道不是限制于某种手法，而是大道无形
2. 量价，形态，是没有固定的标准的，靠大量记忆形成
3. 不可盲目追高
4. 对于已经淘汰的题材，反弹就赶紧走
5. 小资金也要分仓，也不加杠杆，反对梭哈" />
    </node>
  <node TEXT="第15章：总结与行动计划" POSITION="right">
  </node>
    <node TEXT="15.1 92科比心法核心总结" POSITION="right">
      <node TEXT="新生代首板高手" />
      <node TEXT="半年度实盘赛第三名" />
      <node TEXT="模式不固定，灵活多变" />
      <node TEXT="低吸" />
      <node TEXT="追涨" />
    </node>
    <node TEXT="15.2 给初学者的建议" POSITION="right">
      <node TEXT="#### 第一阶段：打好基础（1-3个月）
1. 理解情绪周期四阶段理论
2. 学习基本的技术分析
3. 培养新闻敏感度
4. 小资金练手" />
    </node>
    <node TEXT="15.3 每日自我训练计划" POSITION="right">
      <node TEXT="[ ] 查看隔夜消息" />
      <node TEXT="[ ] 分析昨日涨停板" />
      <node TEXT="[ ] 预判今日热点" />
      <node TEXT="[ ] 制定操作计划" />
      <node TEXT="[ ] 观察大盘走势" />
    </node>
    <node TEXT="15.4 核心要点总结" POSITION="right">
      <node TEXT="1. 92科比心法核心是大道无形
2. 初学者需要循序渐进
3. 每日训练计划很重要
4. 不断学、不断进化
5. 最终形成自己的交易系统" />
    </node>
  <node TEXT="附录：快速参考指南" POSITION="right">
  </node>
    <node TEXT="A. 92科比心法速查表" POSITION="right">
      <node TEXT="| 类别 | 核心内容 | 关键点 |
|------|----------|--------|
| **成长历程** | 新生代首板高手，半年度实盘赛第三名 | 模式不固定，灵活多变 |
| **交..." />
    </node>
    <node TEXT="B. 每日操作检查清单" POSITION="right">
      <node TEXT="[ ] 隔夜消息是否重大？" />
      <node TEXT="[ ] 昨日涨停板质量如何？" />
      <node TEXT="[ ] 今日可能热点是什么？" />
      <node TEXT="[ ] 操作计划是否制定？" />
      <node TEXT="[ ] 大盘走势是否符合预期？" />
    </node>
    <node TEXT="C. 常见错误与纠正" POSITION="right">
      <node TEXT="| 常见错误 | 表现 | 纠正方法 |
|----------|------|----------|
| 局限于某种手法 | 只会一种或几种固定模式 | 做到大道无形，买入即是赚钱的点 |
| 量价..." />
    </node>
    <node TEXT="D. 进阶学资源" POSITION="right">
      <node TEXT="#### 同类型游资心法
1. **小鳄鱼**：超短线核心、二板战法
2. **赵老哥**：连板战法、题材炒作本质
3. **炒股养家**：情绪周期、洞悉市场
4. **Asking**：等待机会、控..." />
    </node>
</node>
</map>