<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="孤独牛背心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 65" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="1. 孤独牛背简介与成长历程" POSITION="right">
  </node>
    <node TEXT="1.1 人物背景" POSITION="right">
      <node TEXT="**网名**：孤独牛背" />
      <node TEXT="**核心标签**：超短梦想系列之控制回撤篇" />
      <node TEXT="**资金体量**：未公开，但属于资深游资" />
      <node TEXT="**风格特点**：控制回撤，超短梦想系列" />
    </node>
    <node TEXT="1.2 成长历程" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
    <node TEXT="1.3 核心成就" POSITION="right">
      <node TEXT="提出"控制回撤"的理念" />
      <node TEXT="总结"多空仓，多看少做"的方法" />
      <node TEXT="提出"仓位控制"的重要性" />
      <node TEXT="总结"交易控制"的原则" />
      <node TEXT="提出"标的控制"的标准" />
    </node>
  <node TEXT="2. 核心交易理念" POSITION="right">
  </node>
    <node TEXT="2.1 控制回撤" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
    </node>
    <node TEXT="2.2 仓位控制" POSITION="right">
      <node TEXT="**单只标的仓位重**：赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
      <node TEXT="**如果可以把资金分成3份**：每份买1只标的，行情好时买满3只标的，行情差时只买1只标的或空仓不做，这样赚钱速度慢了，但回撤幅度大大降低，得之难失之难" />
    </node>
    <node TEXT="2.3 交易控制" POSITION="right">
      <node TEXT="**只做自己熟悉的模式**：亏损也无怨无悔，好的模式出现后，跟风股会跟着大涨，大盘也可能跟着上涨" />
      <node TEXT="**少做无效交易**：无效交易只会侵蚀你的盈利，扰乱你的交易心态。频繁交易只适合手法高的高手，普通选手频繁交易死路一条" />
    </node>
    <node TEXT="2.4 标的控制" POSITION="right">
      <node TEXT="**选择有题材标的**：禁做无题材或题材不明标的，行情好时龙头和跟风股都有肉，行情差时只有做龙头才保险。这样会错过一些潜在利好标的，但个人认为16年的股权变更、高送转 、虚拟现实 、次新股 ，板块个股..." />
    </node>
  <node TEXT="3. 选股体系" POSITION="right">
  </node>
    <node TEXT="3.1 选股的原则" POSITION="right">
      <node TEXT="**选择有题材标的**：禁做无题材或题材不明标的" />
      <node TEXT="**行情好时龙头和跟风股都有肉**：行情差时只有做龙头才保险" />
      <node TEXT="**这样会错过一些潜在利好标的**：但个人认为16年的股权变更、高送转 、虚拟现实 、次新股 ，板块个股众多，已经足够股民做的，何必要舍本逐末？" />
    </node>
    <node TEXT="3.2 选股的方法" POSITION="right">
      <node TEXT="**只做自己熟悉的模式**：亏损也无怨无悔，好的模式出现后，跟风股会跟着大涨，大盘也可能跟着上涨" />
      <node TEXT="**少做无效交易**：无效交易只会侵蚀你的盈利，扰乱你的交易心态" />
    </node>
    <node TEXT="3.3 选股的注意事项" POSITION="right">
      <node TEXT="**频繁交易只适合手法高的高手**：普通选手频繁交易死路一条" />
      <node TEXT="**给你再多的机会**：你也把握不住，何苦呢？" />
    </node>
  <node TEXT="4. 买入时机把握" POSITION="right">
  </node>
    <node TEXT="4.1 买入时机的选择" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="4.2 买入的方法" POSITION="right">
      <node TEXT="**只做自己熟悉的模式**：亏损也无怨无悔，好的模式出现后，跟风股会跟着大涨，大盘也可能跟着上涨" />
      <node TEXT="**少做无效交易**：无效交易只会侵蚀你的盈利，扰乱你的交易心态" />
    </node>
    <node TEXT="4.3 买入的注意事项" POSITION="right">
      <node TEXT="**频繁交易只适合手法高的高手**：普通选手频繁交易死路一条" />
      <node TEXT="**给你再多的机会**：你也把握不住，何苦呢？" />
    </node>
  <node TEXT="5. 持有与卖出策略" POSITION="right">
  </node>
    <node TEXT="5.1 持有策略" POSITION="right">
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
    <node TEXT="5.2 卖出" POSITION="right">
      <node TEXT="**指数气氛**：上证下跌，创业板大跌，是28齐跌，禁止开仓" />
      <node TEXT="**上证大涨，创业板大涨**：是28齐涨，满仓做多" />
    </node>
    <node TEXT="5.3 卖出的方法" POSITION="right">
      <node TEXT="**上证大涨，创业板大跌**：是28分化，小仓位做" />
      <node TEXT="**上证下跌，创业板大涨**：是小盘股气氛好，可买5成以上仓位" />
    </node>
  <node TEXT="6. 仓位管理与资金管理" POSITION="right">
  </node>
    <node TEXT="6.1 仓位管理的原则" POSITION="right">
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
      <node TEXT="**如果可以把资金分成3份**：每份买1只标的，行情好时买满3只标的，行情差时只买1只标的或空仓不做，这样赚钱速度慢了，但回撤幅度大大降低，得之难失之难" />
    </node>
    <node TEXT="6.2 仓位管理的方法" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="6.3 仓位管理的注意事项" POSITION="right">
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
  <node TEXT="7. 风险控制与资金管理" POSITION="right">
  </node>
    <node TEXT="7.1 风险控制的原则" POSITION="right">
      <node TEXT="**控制回撤**：多空仓，多看少做，做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="7.2 风险控制的方法" POSITION="right">
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
    <node TEXT="7.3 风险控制的注意事项" POSITION="right">
      <node TEXT="**指数气氛**：上证下跌，创业板大跌，是28齐跌，禁止开仓" />
      <node TEXT="**上证大涨，创业板大涨**：是28齐涨，满仓做多" />
    </node>
  <node TEXT="8. 心态管理与修身养性" POSITION="right">
  </node>
    <node TEXT="8.1 投资的心态" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="8.2 心态管理的方法" POSITION="right">
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
    <node TEXT="8.3 心态管理的注意事项" POSITION="right">
      <node TEXT="**指数气氛**：上证下跌，创业板大跌，是28齐跌，禁止开仓" />
      <node TEXT="**上证大涨，创业板大涨**：是28齐涨，满仓做多" />
    </node>
  <node TEXT="9. 控制回撤与超短梦想" POSITION="right">
  </node>
    <node TEXT="9.1 如何控制回撤" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="9.2 控制回撤的把握" POSITION="right">
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
    <node TEXT="9.3 控制回撤的注意事项" POSITION="right">
      <node TEXT="**指数气氛**：上证下跌，创业板大跌，是28齐跌，禁止开仓" />
      <node TEXT="**上证大涨，创业板大涨**：是28齐涨，满仓做多" />
    </node>
  <node TEXT="10. 实战案例分析" POSITION="right">
  </node>
    <node TEXT="10.1 控制回撤案例" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="10.2 仓位控制案例" POSITION="right">
      <node TEXT="**如果可以把资金分成3份**：每份买1只标的，行情好时买满3只标的，行情差时只买1只标的或空仓不做，这样赚钱速度慢了，但回撤幅度大大降低，得之难失之难" />
    </node>
    <node TEXT="10.3 交易控制案例" POSITION="right">
      <node TEXT="**只做自己熟悉的模式**：亏损也无怨无悔，好的模式出现后，跟风股会跟着大涨，大盘也可能跟着上涨" />
      <node TEXT="**少做无效交易**：无效交易只会侵蚀你的盈利，扰乱你的交易心态" />
    </node>
  <node TEXT="11. 常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="11.1 误区一：频繁交易" POSITION="right">
      <node TEXT="**纠正**：少做无效交易，无效交易只会侵蚀你的盈利，扰乱你的交易心态。频繁交易只适合手法高的高手，普通选手频繁交易死路一条" />
    </node>
    <node TEXT="11.2 误区二：满仓操作" POSITION="right">
      <node TEXT="**纠正**：仓位控制，单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易。如果可以把资金分成3份，每份买1只标的，行情好时买满3只标的，行情差时只买1只标的或空仓不做，这样赚钱速..." />
    </node>
    <node TEXT="11.3 误区三：做无题材标的" POSITION="right">
      <node TEXT="**纠正**：标的控制，选择有题材标的，禁做无题材或题材不明标的，行情好时龙头和跟风股都有肉，行情差时只有做龙头才保险。这样会错过一些潜在利好标的，但个人认为16年的股权变更、高送转 、虚拟现实 、次..." />
    </node>
    <node TEXT="11.4 误区四：不重视指数气氛" POSITION="right">
      <node TEXT="**纠正**：指数气氛，上证下跌，创业板大跌，是28齐跌，禁止开仓。上证大涨，创业板大涨，是28齐涨，满仓做多。上证大涨，创业板大跌，是28分化，小仓位做。上证下跌，创业板大涨，是小盘股气氛好，可买5..." />
    </node>
    <node TEXT="11.5 误区五：不控制回撤" POSITION="right">
      <node TEXT="**纠正**：控制回撤，多空仓，多看少做，做最强那几只，错过就等，不敢下手就等敢下手" />
    </node>
  <node TEXT="12. 与其他游资的比较" POSITION="right">
  </node>
    <node TEXT="12.1 与炒股养家的比较" POSITION="right">
      <node TEXT="**炒股养家**：注重情绪周期，心法深邃" />
      <node TEXT="**孤独牛背**：注重控制回撤，超短梦想系列" />
    </node>
    <node TEXT="12.2 与Asking的比较" POSITION="right">
      <node TEXT="**Asking**：等待机会，控制回撤" />
      <node TEXT="**孤独牛背**：注重控制回撤，多空仓，多看少做" />
    </node>
    <node TEXT="12.3 与职业炒手的比较" POSITION="right">
      <node TEXT="**职业炒手**：交易本质，弱市操作" />
      <node TEXT="**孤独牛背**：注重控制回撤，超短梦想系列" />
    </node>
  <node TEXT="13. 自我修炼与提升" POSITION="right">
  </node>
    <node TEXT="13.1 学习名家手法" POSITION="right">
      <node TEXT="**多空仓，多看少做**：做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
    </node>
    <node TEXT="13.2 建立自己的交易体系" POSITION="right">
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
    </node>
    <node TEXT="13.3 不断自我否定" POSITION="right">
      <node TEXT="**指数气氛**：上证下跌，创业板大跌，是28齐跌，禁止开仓" />
      <node TEXT="**上证大涨，创业板大涨**：是28齐涨，满仓做多" />
    </node>
    <node TEXT="13.4 做自己看的懂的" POSITION="right">
      <node TEXT="**上证大涨，创业板大跌**：是28分化，小仓位做" />
      <node TEXT="**上证下跌，创业板大涨**：是小盘股气氛好，可买5成以上仓位" />
    </node>
  <node TEXT="14. 总结与核心要点" POSITION="right">
  </node>
    <node TEXT="14.1 核心要点总结" POSITION="right">
      <node TEXT="1. **控制回撤**：多空仓，多看少做，做最强那几只，错过就等，不敢下手就等敢下手
2. **仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易
3. **交易控制..." />
    </node>
    <node TEXT="14.2 交易体系的核心" POSITION="right">
      <node TEXT="**控制回撤**：多空仓，多看少做，做最强那几只，错过就等，不敢下手就等敢下手" />
      <node TEXT="**仓位控制**：单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源，得之易失之易" />
      <node TEXT="**交易控制**：只做自己熟悉的模式，亏损也无怨无悔" />
    </node>
    <node TEXT="14.3 心态管理的核心" POSITION="right">
      <node TEXT="**标的控制**：选择有题材标的，禁做无题材或题材不明标的" />
      <node TEXT="**指数气氛**：上证下跌，创业板大跌，是28齐跌，禁止开仓" />
      <node TEXT="**上证大涨，创业板大涨**：是28齐涨，满仓做多" />
    </node>
  <node TEXT="15. 行动计划与自测题" POSITION="right">
  </node>
    <node TEXT="15.1 行动计划" POSITION="right">
      <node TEXT="学习控制回撤，多空仓，多看少做" />
      <node TEXT="注重仓位控制，单只标的仓位重，赚的多，但遇到亏损回撤幅度也大，盈亏同源" />
      <node TEXT="练习交易控制，只做自己熟悉的模式，亏损也无怨无悔" />
      <node TEXT="建立自己的控制回撤体系，多空仓，多看少做" />
      <node TEXT="练习仓位控制，如果可以把资金分成3份，每份买1只标的" />
    </node>
    <node TEXT="15.2 自测题" POSITION="right">
      <node TEXT="1. 孤独牛背的核心交易理念是什么？
2. 为什么"控制回撤"？
3. 如何选择有题材标的？
4. 为什么"多空仓，多看少做"？
5. 如何控制仓位？
6. 孤独牛背的选股原则是什么？
7. 如何判断..." />
    </node>
    <node TEXT="15.3 实践建议" POSITION="right">
      <node TEXT="1. **每天复盘**：注重控制回撤，多空仓，多看少做
2. **顺势而为**：不轻言底部，不抄底，只做超跌抢反弹
3. **控制仓位**：如果可以把资金分成3份，每份买1只标的
4. **严格执行纪..." />
    </node>
  <node TEXT="附录：孤独牛背心法核心语录" POSITION="right">
    <node TEXT="本文档基于孤独牛背的PDF资料（5页）整理" />
    <node TEXT="结合孤独牛背的实战经验和心法总结" />
    <node TEXT="适合反复阅读和实践，建议每1-2个月重温一次" />
    <node TEXT="结合自己的交易实践，不断修正和完善" />
  </node>
</node>
</map>