<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="龙飞虎心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 65" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第一章：龙飞虎是谁？" POSITION="right">
  </node>
    <node TEXT="1.1 基本信息" POSITION="right">
      <node TEXT="**称号**：龙飞虎" />
      <node TEXT="**代表地位**：动态仓位管理专家，与Asking、职业炒手齐名" />
      <node TEXT="**核心成就**：开创"动态仓位管理"体系，在股灾中仍能盈利" />
    </node>
    <node TEXT="1.2 交易风格特点" POSITION="right">
      <node TEXT="**操作风格**：根据市场变化动态调整仓位" />
      <node TEXT="**核心能力**：对市场情绪的精准把握，对仓位的灵活控制" />
      <node TEXT="**交易理念**：仓位管理比选股更重要，动态适应市场变化" />
    </node>
    <node TEXT="1.3 核心贡献" POSITION="right">
      <node TEXT="**动态仓位管理**：系统化的仓位管理方法" />
      <node TEXT="**股灾抢反弹策略**：在极端市场中的生存之道" />
      <node TEXT="**交易的本质**：对交易深层次的理解" />
    </node>
  <node TEXT="第二章：动态仓位管理（上）" POSITION="right">
  </node>
    <node TEXT="2.1 什么是动态仓位管理？" POSITION="right">
      <node TEXT="根据市场变化动态调整仓位" />
      <node TEXT="不是固定仓位，而是灵活应对" />
      <node TEXT="核心是"顺势加仓，逆势减仓"" />
      <node TEXT="传统：固定仓位（如永远5成仓）" />
      <node TEXT="动态：根据市场变化调整（牛市8成仓，熊市1成仓）" />
    </node>
    <node TEXT="2.2 动态仓位管理的核心原则" POSITION="right">
      <node TEXT="1. **顺势加仓**：趋势向好时逐步加仓
2. **逆势减仓**：趋势转弱时逐步减仓
3. **严格控制**：单只个股不超过5成仓
4. **灵活应对**：根据市场变化及时调整" />
    </node>
    <node TEXT="2.3 市场阶段的判断" POSITION="right">
      <node TEXT="特征：指数上涨，成交量放大，赚钱效应强" />
      <node TEXT="仓位：5-8成仓" />
      <node TEXT="策略：持股为主，适度波段" />
      <node TEXT="特征：指数震荡，成交量萎缩，赚钱效应一般" />
      <node TEXT="仓位：3-5成仓" />
    </node>
  <node TEXT="第三章：动态仓位管理（下）" POSITION="right">
  </node>
    <node TEXT="3.1 仓位调整的触发条件" POSITION="right">
      <node TEXT="大盘突破关键阻力位" />
      <node TEXT="成交量明显放大" />
      <node TEXT="赚钱效应增强" />
      <node TEXT="持仓个股盈利超过5%" />
      <node TEXT="大盘跌破关键支撑位" />
    </node>
    <node TEXT="3.2 仓位调整的具体操作" POSITION="right">
      <node TEXT="**加仓操作**：
1. 确认市场趋势向好
2. 选择最强板块的最强个股
3. 分批加仓，不一次性加满
4. 设置止损，保护利润" />
    </node>
    <node TEXT="3.3 动态仓位管理的常见错误" POSITION="right">
      <node TEXT="表现：市场下跌时反而加仓" />
      <node TEXT="危害：越套越深，亏损巨大" />
      <node TEXT="纠正：逆势要减仓，不能加仓" />
      <node TEXT="表现：市场上涨时不减仓，期待更高" />
      <node TEXT="危害：容易错过止盈时机" />
    </node>
  <node TEXT="第四章：股灾抢反弹策略" POSITION="right">
  </node>
    <node TEXT="4.1 股灾的定义" POSITION="right">
      <node TEXT="**特征**：指数短期暴跌（通常跌幅超过20%）" />
      <node TEXT="**原因**：政策收紧、经济下滑、外部冲击等" />
      <node TEXT="**影响**：市场恐慌，赚钱效应极差" />
    </node>
    <node TEXT="4.2 股灾中的机会" POSITION="right">
      <node TEXT="特征：短期跌幅过大，技术性反弹需求" />
      <node TEXT="操作：快进快出，不恋战" />
      <node TEXT="风险：可能是下跌中继" />
      <node TEXT="特征：政策出手救市，市场企稳" />
      <node TEXT="操作：适度参与，控制仓位" />
    </node>
    <node TEXT="4.3 股灾抢反弹的核心原则" POSITION="right">
      <node TEXT="1. **降低仓位**：股灾中仓位控制在0-3成
2. **快进快出**：不恋战，有盈利就走
3. **严格止损**：股灾中止损要更坚决
4. **精选个股**：只做最强个股" />
    </node>
    <node TEXT="4.4 股灾抢反弹的实战技巧" POSITION="right">
      <node TEXT="找出短期跌幅最大的个股" />
      <node TEXT="判断是否有技术性反弹需求" />
      <node TEXT="选择合适的抢反弹标的" />
      <node TEXT="关注政策动向" />
      <node TEXT="判断是否有政策底" />
    </node>
  <node TEXT="第五章：交易的本质" POSITION="right">
  </node>
    <node TEXT="5.1 交易的本质认知" POSITION="right">
      <node TEXT="交易是概率游戏，不是预测游戏" />
      <node TEXT="盈利来自对的概率和好的赔率" />
      <node TEXT="心态和纪律比技术更重要" />
    </node>
    <node TEXT="5.2 交易的核心要素" POSITION="right">
      <node TEXT="1. **概率**：提高胜率是基础
2. **赔率**：好的买点决定赔率
3. **执行**：严格的纪律是保障" />
    </node>
    <node TEXT="5.3 交易的常见误区" POSITION="right">
      <node TEXT="表现：试图买在最低点，卖在最高点" />
      <node TEXT="危害：容易错过机会，或被套在最高点" />
      <node TEXT="纠正：接受不完美，追求合理收益" />
      <node TEXT="表现：试图预测市场走势" />
      <node TEXT="危害：市场是不可预测的" />
    </node>
  <node TEXT="第六章：选股逻辑" POSITION="right">
  </node>
    <node TEXT="6.1 选股的核心原则" POSITION="right">
      <node TEXT="1. **强势原则**：只做强势股，不做弱势股
2. **龙头原则**：只做龙头，不做跟风
3. **题材原则**：紧跟市场热点题材" />
    </node>
    <node TEXT="6.2 选股的具体标准" POSITION="right">
      <node TEXT="均线多头排列" />
      <node TEXT="成交量放大" />
      <node TEXT="突破关键阻力位" />
      <node TEXT="属于当前市场主流题材" />
      <node TEXT="有政策支持或重大利好" />
    </node>
    <node TEXT="6.3 选股的实战技巧" POSITION="right">
      <node TEXT="每天关注涨幅榜前50名" />
      <node TEXT="找出属于同一板块的个股" />
      <node TEXT="判断是否为题材启动" />
      <node TEXT="每天关注涨停板数量" />
      <node TEXT="找出涨停板最多的板块" />
    </node>
  <node TEXT="第七章：买入时机把握" POSITION="right">
  </node>
    <node TEXT="7.1 最佳买入时机" POSITION="right">
      <node TEXT="优势：情绪波动大，机会多" />
      <node TEXT="风险：容易追高" />
      <node TEXT="策略：观察开盘走势，确认强势后介入" />
      <node TEXT="优势：经过上午的洗盘，午后可能拉升" />
      <node TEXT="风险：如果上午走势弱，午后可能继续弱" />
    </node>
    <node TEXT="7.2 买入的技术信号" POSITION="right">
      <node TEXT="**突破信号**：突破前期高点或关键阻力位" />
      <node TEXT="**放量信号**：成交量明显放大" />
      <node TEXT="**均线支撑**：回踩均线后反弹" />
    </node>
    <node TEXT="7.3 买入的仓位分配" POSITION="right">
      <node TEXT="**试仓**：首次买入2成仓" />
      <node TEXT="**加仓**：确认走势正确后加至3-5成仓" />
      <node TEXT="**满仓**：极少情况下满仓，通常保留2成机动资金" />
    </node>
  <node TEXT="第八章：卖出策略" POSITION="right">
  </node>
    <node TEXT="8.1 卖出的三大原则" POSITION="right">
      <node TEXT="1. **达到预期收益就卖**：不贪心，锁定利润
2. **走势不符合预期就卖**：及时止损，避免更大亏损
3. **大盘变盘就卖**：保住利润，落袋为安" />
    </node>
    <node TEXT="8.2 卖出的具体时机" POSITION="right">
      <node TEXT="达到3-5%收益" />
      <node TEXT="遇到前期高点压力" />
      <node TEXT="成交量萎缩，上涨乏力" />
      <node TEXT="跌破止损线（-3%到-5%）" />
      <node TEXT="走势明显转弱" />
    </node>
    <node TEXT="8.3 卖出的技巧" POSITION="right">
      <node TEXT="**分批卖出**：不要一次性全部卖出" />
      <node TEXT="**跟随趋势**：上升趋势中持有，下降趋势中卖出" />
      <node TEXT="**不要恋战**：超短线不追求卖在最高点" />
    </node>
  <node TEXT="第九章：风险控制" POSITION="right">
  </node>
    <node TEXT="9.1 风险的来源" POSITION="right">
      <node TEXT="1. **市场风险**：大盘下跌带来的系统性风险
2. **个股风险**：个股暴雷、业绩不及预期等
3. **操作风险**：追高、抄底、死扛等错误操作" />
    </node>
    <node TEXT="9.2 风险控制的具体措施" POSITION="right">
      <node TEXT="严格选股，只做强势股" />
      <node TEXT="控制仓位，不重仓单只个股" />
      <node TEXT="设置止损，严格执行" />
      <node TEXT="实时监控盘面变化" />
      <node TEXT="及时调整仓位" />
    </node>
    <node TEXT="9.3 龙飞虎的风险控制金句" POSITION="right">
      <node TEXT="&gt; "止损要坚决，不能拖泥带水。"  
&gt; "保护本金比赚钱更重要。"  
&gt; "风险控制是交易的生命线。"" />
    </node>
  <node TEXT="第十章：心态修炼" POSITION="right">
  </node>
    <node TEXT="10.1 交易心态的重要性" POSITION="right">
      <node TEXT="心态决定执行" />
      <node TEXT="心态影响判断" />
      <node TEXT="心态是交易成功的关键" />
    </node>
    <node TEXT="10.2 常见心态问题" POSITION="right">
      <node TEXT="1. **贪婪**：盈利时不舍得卖
2. **恐惧**：亏损时不敢止损
3. **急躁**：频繁操作，追涨杀跌
4. **侥幸**：死扛亏损单，期待反弹" />
    </node>
    <node TEXT="10.3 心态修炼的方法" POSITION="right">
      <node TEXT="接受亏损是交易的一部分" />
      <node TEXT="理解市场是不可预测的" />
      <node TEXT="明白复利的力量" />
      <node TEXT="制定交易计划并严格执行" />
      <node TEXT="记录交易日志，定期复盘" />
    </node>
  <node TEXT="第十一章：实战案例分析" POSITION="right">
  </node>
    <node TEXT="11.1 案例一：牛市中的动态加仓" POSITION="right">
      <node TEXT="大盘处于牛市阶段" />
      <node TEXT="某题材成为市场主流" />
      <node TEXT="牛市中可以适度加仓" />
      <node TEXT="要敢于持有龙头股" />
      <node TEXT="要在达到预期收益后果断卖出" />
    </node>
    <node TEXT="11.2 案例二：股灾中的抢反弹" POSITION="right">
      <node TEXT="大盘短期暴跌20%" />
      <node TEXT="市场恐慌情绪严重" />
      <node TEXT="股灾中可以抢反弹，但要控制仓位" />
      <node TEXT="要快进快出，不恋战" />
      <node TEXT="要严格止损，保护本金" />
    </node>
  <node TEXT="第十二章：常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="12.1 误区一：逆势加仓" POSITION="right">
      <node TEXT="**表现**：市场下跌时反而加仓  
**危害**：越套越深，亏损巨大  
**纠正**：逆势要减仓，不能加仓" />
    </node>
    <node TEXT="12.2 误区二：仓位过于集中" POSITION="right">
      <node TEXT="**表现**：单只个股仓位超过5成  
**危害**：风险集中，容易爆亏  
**纠正**：单只个股不超过3成仓" />
    </node>
    <node TEXT="12.3 误区三：死扛亏损" POSITION="right">
      <node TEXT="**表现**：亏损后不止损，期待反弹  
**危害**：小亏变大亏，甚至爆仓  
**纠正**：严格止损，止损要坚决" />
    </node>
    <node TEXT="12.4 误区四：忽视仓位管理" POSITION="right">
      <node TEXT="**表现**：不注重仓位管理，随意操作  
**危害**：容易爆亏，资金大幅回撤  
**纠正**：重视仓位管理，动态调整" />
    </node>
  <node TEXT="第十三章：学习要点总结" POSITION="right">
  </node>
    <node TEXT="13.1 核心要点" POSITION="right">
      <node TEXT="1. **动态仓位管理**：根据市场变化动态调整仓位
2. **股灾抢反弹**：控制仓位，快进快出
3. **交易的本质**：概率游戏，心态和纪律更重要
4. **选股逻辑**：强势、龙头、题材三大原..." />
    </node>
    <node TEXT="13.2 实践要求" POSITION="right">
      <node TEXT="✅ 模拟10笔交易" />
      <node TEXT="✅ 实践动态仓位管理" />
      <node TEXT="✅ 写一篇学习总结" />
    </node>
    <node TEXT="13.3 推荐学习路径" POSITION="right">
      <node TEXT="理解动态仓位管理的核心思想" />
      <node TEXT="学习股灾抢反弹策略" />
      <node TEXT="模拟交易练习" />
      <node TEXT="实战操作，小资金试错" />
      <node TEXT="记录交易日志" />
    </node>
  <node TEXT="第十四章：自我检测方法" POSITION="right">
  </node>
    <node TEXT="14.1 基础知识检测（10题）" POSITION="right">
      <node TEXT="1. 龙飞虎的核心交易理念是什么？
2. 什么是动态仓位管理？
3. 市场阶段如何判断？
4. 仓位调整的触发条件有哪些？
5. 股灾中如何抢反弹？
6. 交易的本质是什么？
7. 选股的三大原则是什..." />
    </node>
    <node TEXT="14.2 实战能力检测" POSITION="right">
      <node TEXT="✅ 能否准确判断市场阶段？" />
      <node TEXT="✅ 能否动态调整仓位？" />
      <node TEXT="✅ 能否选出符合标准的强势股？" />
      <node TEXT="✅ 能否果断执行止损？" />
      <node TEXT="✅ 能否控制交易频率？" />
    </node>
    <node TEXT="14.3 进阶标准" POSITION="right">
      <node TEXT="理解龙飞虎的核心思想" />
      <node TEXT="能够模拟交易并有盈利" />
      <node TEXT="形成自己的交易系统" />
      <node TEXT="实盘交易胜率超过50%" />
      <node TEXT="稳定盈利，年化收益超过30%" />
    </node>
  <node TEXT="第十五章：进阶学习资源" POSITION="right">
  </node>
    <node TEXT="15.1 推荐阅读" POSITION="right">
      <node TEXT="《龙飞虎_动态仓位管理》" />
      <node TEXT="《龙飞虎"股灾"抢反弹策略》" />
      <node TEXT="《A神龙飞虎等短线高手感悟》" />
    </node>
    <node TEXT="15.2 推荐关注" POSITION="right">
      <node TEXT="龙飞虎的淘股吧帖子" />
      <node TEXT="与Asking、职业炒手的交流记录" />
    </node>
    <node TEXT="15.3 下一步学习" POSITION="right">
      <node TEXT="学习炒股养家的心法（情绪周期大师）" />
      <node TEXT="学习Asking的心法（短线节奏高手）" />
      <node TEXT="学习赵老哥的心法（连板战法专家）" />
    </node>
  <node TEXT="学习笔记总结" POSITION="right">
  </node>
    <node TEXT="核心收获" POSITION="right">
      <node TEXT="1. **动态仓位管理**：根据市场变化动态调整仓位
2. **股灾抢反弹**：控制仓位，快进快出
3. **交易的本质**：概率游戏，心态和纪律更重要
4. **心态修炼**：心态决定执行，修炼很重..." />
    </node>
    <node TEXT="实践计划" POSITION="right">
      <node TEXT="[ ] 本周模拟10笔交易" />
      <node TEXT="[ ] 下周开始实践动态仓位管理" />
      <node TEXT="[ ] 每月写一篇学习总结" />
    </node>
    <node TEXT="疑问与思考" POSITION="right">
      <node TEXT="1. 如何精准判断市场阶段？
2. 如何克服逆势加仓的冲动？
3. 如何在股灾中控制风险？" />
    </node>
</node>
</map>