<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="欢乐海岸心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 67" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第1章：欢乐海岸简介与成长历程" POSITION="right">
  </node>
    <node TEXT="1.1 个人背景" POSITION="right">
      <node TEXT="**网名**：欢乐海岸" />
      <node TEXT="**席位**：申万宏源深圳金田路营业部（欢乐海岸席位）" />
      <node TEXT="**资金量级**：A级核心游资，资金量估计在数亿级别" />
      <node TEXT="**操作风格**：专做妖股，擅长妖股主升浪和龙回头战法" />
      <node TEXT="**市场地位**：A级核心游资，妖股炒作大师" />
    </node>
    <node TEXT="1.2 操盘特点" POSITION="right">
      <node TEXT="**专注妖股**：专门研究妖股炒作，对妖股有深刻理解" />
      <node TEXT="**系统性复盘**：注重系统性复盘，建立完整的交易体系" />
      <node TEXT="**龙回头战法**：擅长妖股见顶后的龙回头战法" />
      <node TEXT="**趋势为王**：注重主题投资和趋势交易" />
    </node>
    <node TEXT="1.3 核心贡献" POSITION="right">
      <node TEXT="建立了完整的妖股炒作理论体系" />
      <node TEXT="提出"妖股都是M头"的重要观点" />
      <node TEXT="创立"龙回头战法"，丰富妖股炒作手法" />
      <node TEXT="强调系统性复盘的重要性" />
    </node>
  <node TEXT="第2章：核心交易理念" POSITION="right">
  </node>
    <node TEXT="2.1 妖股的本质" POSITION="right">
      <node TEXT="妖股其自身影响力和人气非常强大" />
      <node TEXT="当出现调整后，市场很多人不会立刻相信妖股已经见顶" />
      <node TEXT="而是会去猜测接下来有可能会走第二波第三波第四波主升行情" />
      <node TEXT="因为市场很多参与者都有这种想法，所以妖股见顶后就会出现龙回头" />
    </node>
    <node TEXT="2.2 妖股都是M头" POSITION="right">
      <node TEXT="无论是九鼎新材还是东方通信，都给了龙回头的机会" />
      <node TEXT="妖股不会直接A字下杀，而是会有一个强势反抽的过程" />
      <node TEXT="这个反抽的过程就叫做龙回头" />
      <node TEXT="高点能够逼近前高，甚至是超越前高" />
    </node>
    <node TEXT="2.3 不要恐高" POSITION="right">
      <node TEXT="妖股都是M头，存在次高点" />
      <node TEXT="你们看起来风险很大，但回过头再去看，哪一个妖股会让你们亏很多？" />
      <node TEXT="即使是2月26日东方通信涨停跳水大阴线，不也后面给了新高出局的机会吗？" />
      <node TEXT="实战中只要是妖股，都有新高或者次高出局的位置" />
    </node>
    <node TEXT="2.4 重仓抓取确定性机会" POSITION="right">
      <node TEXT="一年中并没有太多妖股，要是出现妖股的时候你不坚决，不敢上仓位" />
      <node TEXT="即使妖股涨了40％，对你账户来说只盈利了10％，意义并不大" />
      <node TEXT="当机会来临的时候，一定要学会重仓去抓取" />
      <node TEXT="对于一个妖股选手来说，一年中的利润就是靠这么几个股票，其余时间都在等待" />
    </node>
  <node TEXT="第3章：妖股的识别与判断" POSITION="right">
  </node>
    <node TEXT="3.1 什么是妖股？" POSITION="right">
      <node TEXT="妖股是市场地位极高的龙头股" />
      <node TEXT="这个龙头地位是对于市场来说的，并不仅仅是某一板块的龙头" />
      <node TEXT="因为人气太高，网上会给他们取一些特别浮夸的外号" />
      <node TEXT="比如像宇宙总龙头、东方教主等等" />
    </node>
    <node TEXT="3.2 妖股产生的时机" POSITION="right">
      <node TEXT="**妖股产生的市场条件**：
1. **良好的市场环境**：没有股灾、黑天鹅、监管层打压的影响
2. **情绪周期位置**：通常在情绪周期的主升阶段产生
3. **题材够大**：有强大的故事和题材支撑..." />
    </node>
    <node TEXT="3.3 妖股的生命周期" POSITION="right">
      <node TEXT="**妖股的生命周期阶段**：
1. **启动阶段**：从低位启动，开始引起市场关注
2. **主升阶段**：一路分歧或缩量加速，涨幅巨大
3. **加速阶段**：开始缩量加速，这是要当心的信号
4. ..." />
    </node>
  <node TEXT="第4章：妖股参与的时机与方法" POSITION="right">
  </node>
    <node TEXT="4.1 妖股该怎么参与？" POSITION="right">
      <node TEXT="**参与妖股的时机**：
1. **主升阶段**：妖股在主升阶段，可以参与
2. **分歧转一致**：分歧转一致的那一天，其实可做可不做
3. **龙回头阶段**：妖股见顶后的龙回头，是经典的买法" />
    </node>
    <node TEXT="4.2 低吸 vs 打板" POSITION="right">
      <node TEXT="妖股肯定是打板好" />
      <node TEXT="只要封死都能吃肉" />
      <node TEXT="毕竟涨停板是最确定的买点" />
      <node TEXT="如果理解力到位的话，完全可以在分时跳水的时候去低吸" />
      <node TEXT="没必要非等到涨停板，毕竟万一打板没打到呢？" />
    </node>
    <node TEXT="4.3 分歧转一致那天该不该做？" POSITION="right">
      <node TEXT="做妖股的加速是能赚钱的" />
      <node TEXT="但实战中对妖股的把握不可能100％" />
      <node TEXT="要是碰巧去做加速的股不是真妖股的话就容易吃天地板" />
      <node TEXT="其实并不划算" />
      <node TEXT="如果你对妖股的把握有信心，可以做" />
    </node>
  <node TEXT="第5章：妖股的风险控制" POSITION="right">
  </node>
    <node TEXT="5.1 妖股加速的风险" POSITION="right">
      <node TEXT="妖股在出现加速前，一般都不会挂" />
      <node TEXT="妖股开始缩量加速之后，就要当心了" />
      <node TEXT="我放两张图片你们就很清晰了，今年的两个妖股代表东方通信和九鼎新材，见顶都是因为前一天加速，一加速就出现了大阴线" />
      <node TEXT="加速意味着市场一致性过高，获利盘巨大" />
      <node TEXT="一旦加速失败，容易吃天地板" />
    </node>
    <node TEXT="5.2 主升阶段换手的重要性" POSITION="right">
      <node TEXT="最典型的是今年的东方通信，由于它的第三波是一路分歧上来的，所以东方通信见顶后龙回头走出了4个涨停" />
      <node TEXT="与之相反的是去年的万兴科技，主升过程中出现了连续缩量加速，第二波的时候继续加速，所以当大阴线见顶后就再也没有出现龙回头" />
      <node TEXT="筹码结构不断层" />
      <node TEXT="市场平均成本较高，抛压较小" />
      <node TEXT="出现龙回头的几率较大" />
    </node>
    <node TEXT="5.3 止损与纠错" POSITION="right">
      <node TEXT="没有人每次都能看准妖股，炒股做的是概率" />
      <node TEXT="只要你出手10个股票，命中5个是妖股，一年就能赚2倍以上" />
      <node TEXT="所以要是出现看错，误以为这是妖股的情况，切记要果断止损" />
      <node TEXT="亏，最多10％" />
      <node TEXT="赚，却是几十个点的可能" />
    </node>
  <node TEXT="第6章：龙回头战法（核心战法）" POSITION="right">
  </node>
    <node TEXT="6.1 什么是龙回头？" POSITION="right">
      <node TEXT="妖股由于强大的人气，顶部都不是一个点，而是一个区域" />
      <node TEXT="在这个基础之上，才衍生出了龙回头战法" />
      <node TEXT="为什么会出现这种现象？主要是因为妖股其自身影响力和人气非常强大" />
      <node TEXT="当出现调整后，市场很多人不会立刻相信妖股已经见顶，而是会去猜测接下来有可能会走第二波第三波第四波主升行情" />
      <node TEXT="因为市场很多参与者都有这种想法，所以妖股见顶后就会出现龙回头，会有资金愿意去博弈下一波行情" />
    </node>
    <node TEXT="6.2 走出龙回头需要的条件" POSITION="right">
      <node TEXT="既然是龙回头，那本身必须是龙头股" />
      <node TEXT="这个龙头地位是对于市场来说的，并不仅仅是某一板块的龙头" />
      <node TEXT="因为人气太高，网上会给他们取一些特别浮夸的外号，比如像宇宙总龙头、东方教主等等" />
      <node TEXT="他们对盘面有着牵一发而动全身的影响力，一旦下杀，市场其余高位股都会跟风下杀，短线的情绪也会变的极差" />
      <node TEXT="根据我多年妖股实战经验得出的：主升阶段换手越充分的妖股，出现龙回头的几率越大" />
    </node>
    <node TEXT="6.3 龙回头的参与方法" POSITION="right">
      <node TEXT="龙回头本质上是反抽，不是第二波主升" />
      <node TEXT="所以不要期望过高，有利润就走" />
      <node TEXT="不要恋战，走弱就走" />
    </node>
  <node TEXT="第7章：仓位管理与资金管理" POSITION="right">
  </node>
    <node TEXT="7.1 参与妖股的仓位视个人情况而定" POSITION="right">
      <node TEXT="上面我已经跟你们说了，妖股都是M头，存在次高点，你们看起来风险很大，但回过头再去看，哪一个妖股会让你们亏很多？" />
      <node TEXT="即使是2月26日东方通信涨停跳水大阴线，不也后面给了新高出局的机会吗？" />
      <node TEXT="实战中只要是妖股，都有新高或者次高出局的位置" />
      <node TEXT="**如果你做妖股有经验了**：完全可以在确定性的位置满仓干" />
      <node TEXT="**如果你是小白**：从来没玩过妖股，没在妖股上赚过钱，那当然最开始得轻仓体验了" />
    </node>
    <node TEXT="7.2 一年中并没有太多妖股" POSITION="right">
      <node TEXT="当机会来临的时候，一定要学会重仓去抓取" />
      <node TEXT="亏，最多10％，赚，却是几十个点的可能，这种盈亏比不要太划算" />
      <node TEXT="网上所谓的大V肯定说让你们控制仓位参与，实际上这句话就是搞笑" />
      <node TEXT="对于一个妖股选手来说，一年中的利润就是靠这么几个股票，其余时间都在等待" />
    </node>
    <node TEXT="7.3 轻仓体验 vs 重仓抓取" POSITION="right">
      <node TEXT="从来没玩过妖股，没在妖股上赚过钱" />
      <node TEXT="那当然最开始得轻仓体验了" />
      <node TEXT="积累经验，理解妖股的炒作规律" />
      <node TEXT="做妖股有经验了" />
      <node TEXT="完全可以在确定性的位置满仓干" />
    </node>
  <node TEXT="第8章：心态管理与修身养性" POSITION="right">
  </node>
    <node TEXT="8.1 做妖股学会隐忍是必不可少的" POSITION="right">
      <node TEXT="凡是一个股存在成妖的可能，就一定要专注盯牢，随时准备出手" />
      <node TEXT="做妖股学会隐忍是必不可少的" />
      <node TEXT="当妖股出现确定性买点的时候，你不能说那时候我没仓位去买了" />
      <node TEXT="古龙小说里的西门吹雪一年只出门四次，每次只杀一个人，从不失手！" />
      <node TEXT="其余的时间，他只在家做一件事：练剑" />
    </node>
    <node TEXT="8.2 不要存在恐高的心理" POSITION="right">
      <node TEXT="妖股都是M头，是有次高点的，不会直接A字下杀" />
      <node TEXT="你们看起来风险很大，但回过头再去看，哪一个妖股会让你们亏很多？" />
      <node TEXT="即使是2月26日东方通信涨停跳水大阴线，不也后面给了新高出局的机会吗？" />
      <node TEXT="实战中只要是妖股，都有新高或者次高出局的位置" />
    </node>
    <node TEXT="8.3 炒股做的是概率" POSITION="right">
      <node TEXT="没有人每次都能看准妖股，炒股做的是概率" />
      <node TEXT="只要你出手10个股票，命中5个是妖股，一年就能赚2倍以上" />
      <node TEXT="所以要是出现看错，误以为这是妖股的情况，切记要果断止损" />
      <node TEXT="不要因为一次看错就怀疑自己，炒股做的是概率" />
    </node>
  <node TEXT="第9章：系统性复盘" POSITION="right">
  </node>
    <node TEXT="9.1 为什么要系统性复盘？" POSITION="right">
      <node TEXT="复盘是提高自己的唯一途径" />
      <node TEXT="通过复盘，可以总结自己的得失" />
      <node TEXT="通过复盘，可以学习别人的优点" />
      <node TEXT="通过复盘，可以形成自己的交易体系" />
    </node>
    <node TEXT="9.2 怎么系统性复盘？" POSITION="right">
      <node TEXT="**复盘的内容**：
1. **大盘复盘**：分析大盘的走势，判断市场的整体环境
2. **板块复盘**：分析板块的走势，判断市场的热点方向
3. **个股复盘**：分析个股的走势，判断个股的买卖点
..." />
    </node>
    <node TEXT="9.3 如何有效提高炒股水平？" POSITION="right">
      <node TEXT="**提高炒股水平的方法**：
1. **多复盘**：复盘是提高自己的唯一途径
2. **多学习**：学习别人的优点，弥补自己的不足
3. **多总结**：总结自己的得失，形成自己的交易体系
4. **..." />
    </node>
  <node TEXT="第10章：实战案例分析" POSITION="right">
  </node>
    <node TEXT="10.1 东方通信案例（2018-2019年）" POSITION="right">
      <node TEXT="5G题材，东方通信作为5G龙头，涨幅巨大" />
      <node TEXT="从3元多涨到40多元，涨幅超过10倍" />
      <node TEXT="东方通信的第三波是一路分歧上来的，所以见顶后龙回头走出了4个涨停" />
      <node TEXT="主升阶段换手充分，筹码结构不断层" />
      <node TEXT="龙回头给了新高出局的机会" />
    </node>
    <node TEXT="10.2 九鼎新材案例（2019年）" POSITION="right">
      <node TEXT="股权题材，九鼎新材作为股权龙头，涨幅巨大" />
      <node TEXT="九鼎新材也给了龙回头的机会" />
      <node TEXT="妖股都是M头，是有次高点的" />
    </node>
    <node TEXT="10.3 四川双马案例（2016年）" POSITION="right">
      <node TEXT="股权转让题材，四川双马作为股权转让龙头，涨幅巨大" />
      <node TEXT="四川双马是经典的妖股案例" />
      <node TEXT="龙回头走出了多个涨停，利润可观" />
    </node>
  <node TEXT="第11章：常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="11.1 误区一：恐高" POSITION="right">
      <node TEXT="看到股价涨的高了，就不敢买" />
      <node TEXT="认为涨的高的股票风险大" />
    </node>
    <node TEXT="11.2 误区二：过早下车" POSITION="right">
      <node TEXT="妖股刚开始涨，就急于下车" />
      <node TEXT="不敢持有，拿不住" />
      <node TEXT="妖股都是M头，是有次高点的" />
      <node TEXT="持有获取最大的利润" />
    </node>
    <node TEXT="11.3 误区三：重仓参与所有妖股" POSITION="right">
      <node TEXT="看到所有妖股都重仓参与" />
      <node TEXT="不考虑自己的经验和理解力" />
      <node TEXT="如果你做妖股有经验了，完全可以在确定性的位置满仓干" />
      <node TEXT="如果你是小白，从来没玩过妖股，没在妖股上赚过钱，那当然最开始得轻仓体验了" />
    </node>
    <node TEXT="11.4 误区四：不懂隐忍" POSITION="right">
      <node TEXT="没有耐心，频繁操作" />
      <node TEXT="当妖股出现确定性买点的时候，没仓位去买了" />
    </node>
    <node TEXT="11.5 误区五：期望龙回头是第二波主升" POSITION="right">
      <node TEXT="认为龙回头是第二波主升" />
      <node TEXT="期望过高，恋战不走" />
      <node TEXT="龙回头本质上是反抽，不是第二波主升" />
      <node TEXT="所以不要期望过高，有利润就走" />
      <node TEXT="不要恋战，走弱就走" />
    </node>
  <node TEXT="第12章：与其他游资的比较" POSITION="right">
  </node>
    <node TEXT="12.1 与炒股养家的比较" POSITION="right">
      <node TEXT="都注重市场情绪和人气" />
      <node TEXT="都有自己完整的交易体系" />
      <node TEXT="炒股养家更注重情绪周期，欢乐海岸更注重妖股炒作" />
      <node TEXT="炒股养家更稳健，欢乐海岸更激进" />
    </node>
    <node TEXT="12.2 与赵老哥的比较" POSITION="right">
      <node TEXT="都擅长龙头战法" />
      <node TEXT="都注重题材炒作" />
      <node TEXT="赵老哥更注重连板战法，欢乐海岸更注重妖股炒作" />
      <node TEXT="赵老哥更注重题材，欢乐海岸更注重人气" />
    </node>
    <node TEXT="12.3 与著名刺客的比较" POSITION="right">
      <node TEXT="都擅长龙头战法" />
      <node TEXT="都注重人气情绪" />
      <node TEXT="著名刺客更注重情绪逆转大长腿，欢乐海岸更注重妖股主升浪和龙回头" />
      <node TEXT="著名刺客更注重买点，欢乐海岸更注重仓位管理" />
    </node>
  <node TEXT="第13章：自我修炼与提升" POSITION="right">
  </node>
    <node TEXT="13.1 系统性复盘" POSITION="right">
      <node TEXT="欢乐海岸注重系统性复盘" />
      <node TEXT="建立完整的交易体系" />
    </node>
    <node TEXT="13.2 学习名家手法" POSITION="right">
      <node TEXT="学习其他游资的优点" />
      <node TEXT="不断锤炼自己" />
    </node>
    <node TEXT="13.3 不断自我否定" POSITION="right">
      <node TEXT="即使现在是大游资，不进则退" />
      <node TEXT="必须不断学习，不断进步" />
    </node>
    <node TEXT="13.4 做自己看的懂的" POSITION="right">
      <node TEXT="只做自己看的懂的" />
      <node TEXT="赚自己模式的钱" />
    </node>
  <node TEXT="第14章：总结与核心要点" POSITION="right">
  </node>
    <node TEXT="14.1 核心理念" POSITION="right">
      <node TEXT="1. **妖股都是M头**，是有次高点的，不会直接A字下杀
2. **做妖股，一定不要存在恐高的心理**，往往涨的越高的股票越安全的
3. **当机会来临的时候，一定要学会重仓去抓取**
4. **做..." />
    </node>
    <node TEXT="14.2 妖股炒作的核心" POSITION="right">
      <node TEXT="1. **妖股在出现加速前，一般都不会挂**
2. **妖股开始缩量加速之后，就要当心了**
3. **主升阶段换手越充分的妖股，出现龙回头的几率越大**
4. **妖股都是M头，是有次高点的**" />
    </node>
    <node TEXT="14.3 龙回头战法" POSITION="right">
      <node TEXT="1. **妖股在做顶的过程中，都会有一个强势反抽的过程**
2. **走出龙回头需要的条件**：市场地位、筹码结构不能断层、要有一定的回调空间、良好的市场环境
3. **龙回头的本质是反抽，不是第二波..." />
    </node>
    <node TEXT="14.4 风险控制" POSITION="right">
      <node TEXT="1. **妖股开始缩量加速之后，就要当心了**
2. **主升阶段换手越充分越好**
3. **没有人每次都能看准妖股，炒股做的是概率**
4. **要是出现看错，误以为这是妖股的情况，切记要果断止损..." />
    </node>
    <node TEXT="14.5 心态管理" POSITION="right">
      <node TEXT="1. **做妖股，一定不要存在恐高的心理**
2. **做妖股学会隐忍是必不可少的**
3. **炒股做的是概率，只要你出手10个股票，命中5个是妖股，一年就能赚2倍以上**" />
    </node>
  <node TEXT="第15章：行动计划与自测题" POSITION="right">
  </node>
    <node TEXT="15.1 30天行动计划" POSITION="right">
      <node TEXT="[ ] 阅读欢乐海岸的经典文章3遍" />
      <node TEXT="[ ] 理解"妖股都是M头"的深刻含义" />
      <node TEXT="[ ] 总结自己过去参与妖股的误区" />
      <node TEXT="[ ] 制定"不恐高"的操作纪律" />
      <node TEXT="[ ] 深入研究妖股的定义和特征" />
    </node>
    <node TEXT="15.2 核心要点检查清单" POSITION="right">
      <node TEXT="[ ] 我是在做妖股，还是在做普通股票？" />
      <node TEXT="[ ] 我理解妖股的本质吗？" />
      <node TEXT="[ ] 我存在恐高的心理吗？" />
      <node TEXT="[ ] 我学会了隐忍吗？" />
      <node TEXT="[ ] 这是妖股吗？" />
    </node>
    <node TEXT="15.3 每日自测题" POSITION="right">
      <node TEXT="**基础题（必做）**：
1. 妖股的本质是什么？（答案：妖股由于强大的人气，顶部都不是一个点，而是一个区域）
2. 妖股都是什么头？（答案：M头）
3. 做妖股要不要恐高？（答案：不要，往往涨的越高..." />
    </node>
  <node TEXT="附录：欢乐海岸经典语录" POSITION="right">
    <node TEXT="1. **关于妖股的本质**：
   &gt; 妖股由于强大的人气，顶部都不是一个点，而是一个区域。" />
  </node>
</node>
</map>