<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<map version="1.0.1">
<!-- Generated by WorkBuddy -->
<node TEXT="著名刺客心法" FOLDED="false" POSITION="right">
  <node TEXT="📊 学习概览" POSITION="right">
    <node TEXT="总章节数: 71" />
    <node TEXT="学习状态: ✅已完成" />
    <node TEXT="笔记格式: Markdown" />
  </node>
  <node TEXT="第1章：著名刺客简介与成长历程" POSITION="right">
  </node>
    <node TEXT="1.1 个人背景" POSITION="right">
      <node TEXT="**真名**：不详（网名"著名刺客"）" />
      <node TEXT="**出生年代**：80后/90后（湖南人）" />
      <node TEXT="**教育背景**：985名校高材生，硕士研究生毕业" />
      <node TEXT="**职业背景**：从事研发工作后开始业余炒股" />
      <node TEXT="**入市时间**：2013年四五月份" />
    </node>
    <node TEXT="1.2 资金增长历程" POSITION="right">
      <node TEXT="**2013年**：入市第一年，亏损约30%" />
      <node TEXT="**2014年底**：资金达到将近19万" />
      <node TEXT="**2015年6月**：资金量达到近90万" />
      <node TEXT="**2015年底**：资金量大概二三百万左右" />
      <node TEXT="**2016年10月24日**：资金量是642万" />
    </node>
    <node TEXT="1.3 操盘席位" POSITION="right">
      <node TEXT="**席位**：海通证券北京阜外大街营业部" />
    </node>
    <node TEXT="1.4 成长关键词" POSITION="right">
      <node TEXT="**名校高材生**：985名校硕士，理论基础扎实" />
      <node TEXT="**业余炒股**：从事研发工作后开始业余炒股" />
      <node TEXT="**参赛磨砺**：参加过其它炒股比赛而亏损退赛" />
      <node TEXT="**学习名家**：之后学习了不少名家的操盘手法，不断锤炼自己" />
      <node TEXT="**改变手法**：2014年4月份改变之前的操盘手法，以只做龙头股为主" />
    </node>
  <node TEXT="第2章：核心交易理念" POSITION="right">
  </node>
    <node TEXT="2.1 核心宗旨" POSITION="right">
      <node TEXT="很多打板选手随便打个板，第二天高开就走，以为这就是稳定复利 —— **差矣！**" />
      <node TEXT="打板的真正目的：**在最后确定的一瞬间买入市场上最强的个股，持有获取最大的利润**" />
      <node TEXT="打板不是目的，做到龙头个股才是目的" />
    </node>
    <node TEXT="2.2 小资金出路" POSITION="right">
      <node TEXT="不要在弱势个股中耽误时间，不参与调整" />
      <node TEXT="被套后不要死拿，选错股不会妨碍我们做大，打板大面也不会妨碍我们做大 —— **但是时间会！**" />
      <node TEXT="坚决果断的认错出局，重新投入新的战斗" />
      <node TEXT="让资金流动起来，跟随最热的热点，趁着牛市的东风，才能迅速做大" />
    </node>
    <node TEXT="2.3 主流的重要性" POSITION="right">
      <node TEXT="市场最大的主力就是散户，得散户心得天下，主力也要顺势而为" />
      <node TEXT="长线研究行业趋势，短线研究市场合力" />
      <node TEXT="没有确定的模式，这是致命的，熊市一来，肯定全部还回去" />
    </node>
    <node TEXT="2.4 正确的操作观" POSITION="right">
      <node TEXT="炒股为了赚钱，但赚钱的目的，是让身边的人过的更好，是为了修身养性，遇见更好的自己" />
      <node TEXT="家里长辈一直教导，厚道善良、守信诚实、谦虚执着，是立身之本" />
      <node TEXT="没有这些，单纯追求钱，也是本末倒置" />
    </node>
  <node TEXT="第3章：四大操盘手法" POSITION="right">
  </node>
    <node TEXT="3.1 连板战法" POSITION="right">
      <node TEXT="连板出大牛，是很多操盘席位都善于运用的战法" />
      <node TEXT="是很多操盘手的主力操盘手法，因为只有连板才最容易捕捉到大牛股" />
      <node TEXT="对于换手连板投入的资金仓位较多" />
      <node TEXT="对于缩量板投入的兵力就比较少" />
      <node TEXT="重点关注换手连板，而不是缩量板" />
    </node>
    <node TEXT="3.2 主线情绪逆转大长腿（核心战法）" POSITION="right">
      <node TEXT="情绪由恐惧，到极度贪婪，当天人的贪婪和恐惧表现的淋漓尽致" />
      <node TEXT="分歧到一致，从水下到直线拉板，暴力美学，吸引市场足够的目光" />
      <node TEXT="大部分是主线龙头打出空间之后的情绪补涨龙头" />
      <node TEXT="大多发生在临近午盘收盘接近11点30分，下午1点开盘前10分钟，及下午14点，这些整点时刻" />
      <node TEXT="不知道是不是刻意为之，整数点更容易吸引市场的目光，聚集更多的人气" />
    </node>
    <node TEXT="3.3 临近收盘偷袭，拉尾盘（尾盘战法）" POSITION="right">
      <node TEXT="尤其是叠加次新的前期强势个股高位反包" />
      <node TEXT="乔帮主、成都帮也经常使用这种方法" />
      <node TEXT="乔帮主、刺客和成都帮的不同是：乔帮主和刺客经常拉升超短资金喜爱的次新股，而成都帮拉升的更多是冷门股" />
      <node TEXT="华森制药" />
      <node TEXT="卫信康" />
    </node>
    <node TEXT="3.4 围绕当时主线热点的首板打板操作" POSITION="right">
      <node TEXT="尤其是叠加次新的首板" />
      <node TEXT="例如：嘉城国际（上海自贸港叠加次新）、爱乐达（毛衣战，军工受益叠加次新）" />
      <node TEXT="首板打板操作需要围绕当时主线热点" />
      <node TEXT="叠加次新的首板优先关注" />
    </node>
  <node TEXT="第4章：刺客模式深度解析" POSITION="right">
  </node>
    <node TEXT="4.1 刺客模式的核心" POSITION="right">
      <node TEXT="他的交易背后核心是人气情绪" />
      <node TEXT="即主线行情中的人气股第一次极端情绪表达" />
      <node TEXT="从极端恐慌逆转到极端贪婪，股价往往是大跌逆转拉出大长腿一般的涨停板" />
    </node>
    <node TEXT="4.2 刺客模式的要素" POSITION="right">
      <node TEXT="例：次新股、区块链、上海自贸港等" />
      <node TEXT="例：贵州燃气（低价次新股）、易见股份（区块链一字板）" />
      <node TEXT="例：招商公路（从跌停直接拉到涨停）、壹桥股份（老庄股被重新激活）" />
    </node>
    <node TEXT="4.3 经典交易案例分析" POSITION="right">
      <node TEXT="低价次新股贵州燃气拉出接近7个涨停" />
      <node TEXT="在低价新股投机情绪最疯狂的爆点是12月26日贵州燃气打出了5涨停" />
      <node TEXT="那个时候连30个亿的华能水电都能打出连板" />
      <node TEXT="市场对低价新股产生了强大的追高情绪" />
      <node TEXT="招商公路作为一个换股上市的类新股，上市第二天从跌停直接拉到涨停" />
    </node>
  <node TEXT="第5章：买点与卖点把握" POSITION="right">
  </node>
    <node TEXT="5.1 买点选择" POSITION="right">
      <node TEXT="临近午盘收盘接近11点30分" />
      <node TEXT="下午1点开盘前10分钟" />
      <node TEXT="下午14点" />
      <node TEXT="这些整点时刻，整数点更容易吸引市场的目光，聚集更多的人气" />
    </node>
    <node TEXT="5.2 卖点选择" POSITION="right">
      <node TEXT="招商公路：一字板后锁仓了一天再砸盘而出" />
      <node TEXT="壹桥股份：判断区块链主流人气情绪持续的时间有多久，决定了持续交易的时间长度" />
    </node>
    <node TEXT="5.3 不要测顶，不要抄底" POSITION="right">
      <node TEXT="测顶和抄底都是徒劳的，因为你只能对一次" />
      <node TEXT="顶和底都只有一个，不要试图去预测" />
      <node TEXT="跟随市场，而不是预测市场" />
    </node>
  <node TEXT="第6章：风险控制与资金管理" POSITION="right">
  </node>
    <node TEXT="6.1 防守决定高度" POSITION="right">
      <node TEXT="我不打，因为我看不懂" />
      <node TEXT="我也只能理解很小一部分的市场，做自己看的懂的" />
      <node TEXT="赚自己模式的钱，只赚自己能力范围内看的懂的钱，这是股市生存之道" />
    </node>
    <node TEXT="6.2 坚决果断的认错出局" POSITION="right">
      <node TEXT="选错股不会妨碍我们做大，打板大面也不会妨碍我们做大 —— **但是时间会！**" />
      <node TEXT="被套后不要死拿，不要在弱势个股中耽误时间" />
      <node TEXT="不参与调整，让资金流动起来，跟随最热的热点" />
    </node>
    <node TEXT="6.3 空仓的艺术" POSITION="right">
      <node TEXT="不要为了操作而操作，不要为了打板而打板" />
      <node TEXT="如果尾盘选不出哪个板会吃大肉，就空着" />
      <node TEXT="空仓也是一种操作，等待确定性机会" />
    </node>
    <node TEXT="6.4 不过度交易" POSITION="right">
      <node TEXT="只做自己看的懂的，赚自己模式的钱" />
      <node TEXT="只赚自己能力范围内看的懂的钱" />
      <node TEXT="这是股市生存之道" />
    </node>
  <node TEXT="第7章：心态管理与修身养性" POSITION="right">
  </node>
    <node TEXT="7.1 炒股的目的" POSITION="right">
      <node TEXT="家里长辈一直教导，厚道善良、守信诚实、谦虚执着，是立身之本" />
      <node TEXT="没有这些，单纯追求钱，也是本末倒置" />
      <node TEXT="虽然刺客做的还很不够，但一直在朝这些方面要求自己" />
    </node>
    <node TEXT="7.2 操作股票的正确心态" POSITION="right">
      <node TEXT="不要一直想着挣钱，那样会扭曲心态" />
      <node TEXT="只需做正确的操作，不管盈亏" />
      <node TEXT="赚钱只是正确操作的附加品，不是目的" />
    </node>
    <node TEXT="7.3 量能萎缩时的心态" POSITION="right">
      <node TEXT="量能萎缩，行情趋于无聊，职业炒股还是枯燥寂寞" />
      <node TEXT="不要在行情无聊时强行操作，那是亏损之源" />
      <node TEXT="保持耐心，等待机会" />
    </node>
    <node TEXT="7.4 不断进步的心态" POSITION="right">
      <node TEXT="市场在不断变化，必须不断学习，不断进步" />
      <node TEXT="固步自封，最终会走向没落" />
      <node TEXT="最强的，最硬的板，不是看封单大不大、涨停时间早不早，而是看第二天接力的人能不能赚钱" />
    </node>
  <node TEXT="第8章：技术分析的精髓" POSITION="right">
  </node>
    <node TEXT="8.1 技术不是最重要的" POSITION="right">
      <node TEXT="技术分析只是工具，不是目的" />
      <node TEXT="脱离主流，技术分析毫无意义" />
      <node TEXT="主流才是核心，技术分析只是辅助" />
    </node>
    <node TEXT="8.2 最强的板的标准" POSITION="right">
      <node TEXT="封单大不大、涨停时间早不早，都不是最重要的" />
      <node TEXT="最重要的是第二天接力的人能不能赚钱" />
      <node TEXT="只有共赢的板，才是心中最强的板" />
    </node>
    <node TEXT="8.3 万法归一" POSITION="right">
      <node TEXT="低吸、追涨、打板、尾盘潜伏，这些都只是方法" />
      <node TEXT="核心是万法归一，紧随主流做" />
      <node TEXT="再结合分析收益率，那就是暴利" />
    </node>
  <node TEXT="第9章：市场合力与散户力量" POSITION="right">
  </node>
    <node TEXT="9.1 市场最大的主力" POSITION="right">
      <node TEXT="不要担心主力出货的一批人，都还需要进步" />
      <node TEXT="市场最大的主力就是散户" />
      <node TEXT="得散户心得天下，主力也要顺势而为" />
    </node>
    <node TEXT="9.2 短线研究市场合力" POSITION="right">
      <node TEXT="长线和短线的研究方法不同" />
      <node TEXT="长线研究行业趋势，短线研究市场合力和主流热点" />
      <node TEXT="没有确定的模式，这是致命的，熊市一来，肯定全部还回去" />
    </node>
    <node TEXT="9.3 人气情绪的持续性" POSITION="right">
      <node TEXT="刺客模式的核心是判断主线人气情绪的持续时间" />
      <node TEXT="人气情绪持续的时间有多久，决定了持续交易的时间长度" />
      <node TEXT="直到主线整体人气下降后再选择离场" />
    </node>
  <node TEXT="第10章：实战案例分析" POSITION="right">
  </node>
    <node TEXT="10.1 招商公路案例（2017年12月）" POSITION="right">
      <node TEXT="低价次新股贵州燃气拉出接近7个涨停" />
      <node TEXT="市场对低价新股产生了强大的追高情绪" />
      <node TEXT="市场把招商公路当成了低价新股来炒作" />
      <node TEXT="这是他情绪逆转天地板最根本的原因" />
      <node TEXT="市场如果因为股价的逆转重新认识到招商公路是低价次新股的话" />
    </node>
    <node TEXT="10.2 壹桥股份案例（2018年1月）" POSITION="right">
      <node TEXT="区块链风口，易见股份连续一字板" />
      <node TEXT="整个区块链的情绪太过于强大，踏空的游资充满了躁动的情绪" />
      <node TEXT="壹桥股份在这样一个情绪背景之下产生的逆转板" />
      <node TEXT="区块链情绪重新逆转将股价封死涨停" />
      <node TEXT="整个区块链主流人气情绪持续的时间有多久，决定了持续交易的时间长度" />
    </node>
    <node TEXT="10.3 华森制药、卫信康案例（尾盘战法）" POSITION="right">
      <node TEXT="临近收盘偷袭拉升尾盘" />
      <node TEXT="尤其是叠加次新的前期强势个股高位反包" />
      <node TEXT="即使炸板，回落时间有限，第二天可以择机处理" />
      <node TEXT="不像早盘板，一旦炸板，下跌时间太长，导致风险不可控" />
    </node>
  <node TEXT="第11章：常见误区与纠正" POSITION="right">
  </node>
    <node TEXT="11.1 误区一：打板就是为了打板" POSITION="right">
      <node TEXT="很多打板选手随便打个板，第二天高开就走，以为这就是稳定复利" />
    </node>
    <node TEXT="11.2 误区二：过度关注技术" POSITION="right">
      <node TEXT="过度关注KDJ、均线、数浪、缠论等技术指标" />
      <node TEXT="脱离主流，过度依赖技术分析" />
    </node>
    <node TEXT="11.3 误区三：测顶和抄底" POSITION="right">
      <node TEXT="试图测顶和抄底" />
      <node TEXT="所有的测顶，你只能对一次，因为顶只有一个" />
      <node TEXT="所有的抄底，你只能对一次，因为底只有一个" />
      <node TEXT="不要测顶，不要抄底" />
      <node TEXT="跟随市场，而不是预测市场" />
    </node>
    <node TEXT="11.4 误区四：被套后死拿" POSITION="right">
      <node TEXT="被套后死拿，不参与调整" />
      <node TEXT="在弱势个股中耽误时间" />
    </node>
    <node TEXT="11.5 误区五：过度交易" POSITION="right">
      <node TEXT="为了操作而操作，为了打板而打板" />
      <node TEXT="尾盘选不出哪个板会吃大肉，还强行操作" />
    </node>
  <node TEXT="第12章：与其他游资的比较" POSITION="right">
  </node>
    <node TEXT="12.1 与乔帮主的比较" POSITION="right">
      <node TEXT="都善于临近收盘偷袭拉升尾盘" />
      <node TEXT="都经常拉升超短资金喜爱的次新股" />
      <node TEXT="乔帮主更擅长低吸，刺客更擅长打板" />
      <node TEXT="乔帮主更注重题材，刺客更注重人气情绪" />
    </node>
    <node TEXT="12.2 与成都帮的比较" POSITION="right">
      <node TEXT="都善于临近收盘偷袭拉升尾盘" />
      <node TEXT="成都帮拉升的更多是冷门股" />
      <node TEXT="乔帮主和刺客经常拉升超短资金喜爱的次新股" />
    </node>
    <node TEXT="12.3 与炒股养家的比较" POSITION="right">
      <node TEXT="都注重市场情绪和人气" />
      <node TEXT="都有自己完整的交易体系" />
      <node TEXT="炒股养家更注重情绪周期，刺客更注重人气情绪的逆转" />
      <node TEXT="炒股养家更稳健，刺客更激进" />
    </node>
  <node TEXT="第13章：自我修炼与提升" POSITION="right">
  </node>
    <node TEXT="13.1 学习名家手法" POSITION="right">
      <node TEXT="著名刺客在成长过程中，学习了不少名家的操盘手法" />
      <node TEXT="不断锤炼自己，才能快速进步" />
    </node>
    <node TEXT="13.2 改变操盘手法" POSITION="right">
      <node TEXT="2014年4月份改变之前的操盘手法，以只做龙头股为主" />
      <node TEXT="加上各种潜伏、盘前消息操作及涨停接力，资金量快速上涨" />
    </node>
    <node TEXT="13.3 不断自我否定" POSITION="right">
      <node TEXT="即使现在是大游资，不进则退，固步自封，无异于清政府的闭关锁国，最终会走向没落" />
      <node TEXT="必须不断学习，不断进步" />
    </node>
    <node TEXT="13.4 做自己看的懂的" POSITION="right">
      <node TEXT="&gt; **我也只能理解很小一部分的市场，做自己看的懂的，赚自己模式的钱，只赚自己能力范围内看的懂的钱，这是股市生存之道。**" />
    </node>
  <node TEXT="第14章：总结与核心要点" POSITION="right">
  </node>
    <node TEXT="14.1 核心理念" POSITION="right">
      <node TEXT="1. **打板是为了做到龙头个股**，而不是简单的打板套利
2. **小资金，跟随主流是我们唯一的出路**
3. **时间是我们最大的敌人**，不要在弱势个股中耽误时间
4. **脱离主流，只有死路一..." />
    </node>
    <node TEXT="14.2 四大操盘手法" POSITION="right">
      <node TEXT="1. **连板战法**：对于换手连板投入的资金仓位较多
2. **主线情绪逆转大长腿**：情绪由恐惧到贪婪，分歧转为一致
3. **临近收盘偷袭拉尾盘**：尤其是叠加次新的前期强势个股高位反包
4. ..." />
    </node>
    <node TEXT="14.3 刺客模式的核心" POSITION="right">
      <node TEXT="**主线，人气核心，情绪波动，核心人气品种的第一次大长腿**" />
      <node TEXT="交易背后核心是人气情绪" />
      <node TEXT="即主线行情中的人气股第一次极端情绪表达" />
    </node>
    <node TEXT="14.4 风险控制" POSITION="right">
      <node TEXT="1. **防守决定股市旅程的高度**
2. **坚决果断的认错出局**，重新投入新的战斗
3. **空仓也是一种操作**，等待确定性机会" />
    </node>
    <node TEXT="14.5 心态管理" POSITION="right">
      <node TEXT="1. **操作股票，不应一直想着挣钱**，只需做正确的操作
2. **赚钱只是正确操作的附加品**，本末不能倒置
3. **炒股为了赚钱，但赚钱的目的，是让身边的人过的更好**" />
    </node>
  <node TEXT="第15章：行动计划与自测题" POSITION="right">
  </node>
    <node TEXT="15.1 30天行动计划" POSITION="right">
      <node TEXT="[ ] 阅读著名刺客的经典语录3遍" />
      <node TEXT="[ ] 理解"打板是为了做到龙头个股"的深刻含义" />
      <node TEXT="[ ] 总结自己过去打板操作的误区" />
      <node TEXT="[ ] 制定"只做龙头个股"的操作纪律" />
      <node TEXT="[ ] 深入研究连板战法，总结换手连板和缩量板的区别" />
    </node>
    <node TEXT="15.2 核心要点检查清单" POSITION="right">
      <node TEXT="[ ] 我是在做龙头个股，还是简单的打板套利？" />
      <node TEXT="[ ] 我是在跟随主流，还是偏离主流？" />
      <node TEXT="[ ] 我理解当前的市场情绪吗？" />
      <node TEXT="[ ] 我是在做自己看的懂的，还是盲目操作？" />
      <node TEXT="[ ] 这是主线行情中的人气股第一次极端情绪表达吗？" />
    </node>
    <node TEXT="15.3 每日自测题" POSITION="right">
      <node TEXT="**基础题（必做）**：
1. 刺客模式的核心是什么？（答案：主线，人气核心，情绪波动，核心人气品种的第一次大长腿）
2. 打板的真正目的是什么？（答案：在最后确定的一瞬间买入市场上最强的个股，持有获..." />
    </node>
  <node TEXT="附录：著名刺客经典语录" POSITION="right">
    <node TEXT="1. **关于打板**：
   &gt; 打板也好，低吸也好，追涨也好，目的就是要做到龙头个股，而不是简单的打板套利。市场很多的打板选手，随便打个板，第二天高开就走，以为这就是稳定复利，差矣；打板是为..." />
  </node>
</node>
</map>